/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module qca_qck_gating(clk, rst_n, qck_in, qck_n_in, qca_in, bcw_qck_enable, bcw_qca_enable, bcw_gate_mode, bcw_cal_mode, gate_enable, cal_enable, power_down, qck_out, qck_n_out, qca_out, cal_start, cal_target_phase, cal_done, cal_current_phase, cal_locked, qck_gated
, qca_gated, gate_status);
  wire [15:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [7:0] _026_;
  wire [3:0] _027_;
  wire [1:0] _028_;
  wire [3:0] _029_;
  wire [1:0] _030_;
  wire [3:0] _031_;
  wire [1:0] _032_;
  wire [3:0] _033_;
  wire [1:0] _034_;
  wire [3:0] _035_;
  wire [1:0] _036_;
  wire [3:0] _037_;
  wire [1:0] _038_;
  wire [3:0] _039_;
  wire [1:0] _040_;
  wire [3:0] _041_;
  wire [1:0] _042_;
  wire [3:0] _043_;
  wire [1:0] _044_;
  wire [3:0] _045_;
  wire [1:0] _046_;
  wire [3:0] _047_;
  wire [1:0] _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire [2:0] _053_;
  wire [1:0] _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire [7:0] _088_;
  wire [7:0] _089_;
  wire [7:0] _090_;
  wire [7:0] _091_;
  wire [7:0] _092_;
  wire [7:0] _093_;
  wire [7:0] _094_;
  wire [7:0] _095_;
  wire [7:0] _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire [7:0] _101_;
  wire [7:0] _102_;
  wire [7:0] _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire [31:0] _113_;
  wire [31:0] _114_;
  wire [31:0] _115_;
  wire [31:0] _116_;
  wire [31:0] _117_;
  wire [31:0] _118_;
  wire [31:0] _119_;
  wire [31:0] _120_;
  wire [31:0] _121_;
  wire [7:0] _122_;
  wire [7:0] _123_;
  wire [7:0] _124_;
  wire [7:0] _125_;
  wire _126_;
  wire _127_;
  wire [7:0] _128_;
  wire [7:0] _129_;
  wire _130_;
  wire _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  input [7:0] bcw_cal_mode;
  wire [7:0] bcw_cal_mode;
  input [7:0] bcw_gate_mode;
  wire [7:0] bcw_gate_mode;
  input [7:0] bcw_qca_enable;
  wire [7:0] bcw_qca_enable;
  input [7:0] bcw_qck_enable;
  wire [7:0] bcw_qck_enable;
  wire [15:0] cal_counter;
  output [7:0] cal_current_phase;
  wire [7:0] cal_current_phase;
  output cal_done;
  wire cal_done;
  input cal_enable;
  wire cal_enable;
  output cal_locked;
  wire cal_locked;
  input cal_start;
  wire cal_start;
  input [7:0] cal_target_phase;
  wire [7:0] cal_target_phase;
  wire calibration_active;
  input clk;
  wire clk;
  wire [7:0] \delay_chain_qca[0] ;
  wire [7:0] \delay_chain_qca[10] ;
  wire [7:0] \delay_chain_qca[11] ;
  wire [7:0] \delay_chain_qca[12] ;
  wire [7:0] \delay_chain_qca[13] ;
  wire [7:0] \delay_chain_qca[14] ;
  wire [7:0] \delay_chain_qca[15] ;
  wire [7:0] \delay_chain_qca[16] ;
  wire [7:0] \delay_chain_qca[17] ;
  wire [7:0] \delay_chain_qca[18] ;
  wire [7:0] \delay_chain_qca[19] ;
  wire [7:0] \delay_chain_qca[1] ;
  wire [7:0] \delay_chain_qca[20] ;
  wire [7:0] \delay_chain_qca[21] ;
  wire [7:0] \delay_chain_qca[22] ;
  wire [7:0] \delay_chain_qca[23] ;
  wire [7:0] \delay_chain_qca[24] ;
  wire [7:0] \delay_chain_qca[25] ;
  wire [7:0] \delay_chain_qca[26] ;
  wire [7:0] \delay_chain_qca[27] ;
  wire [7:0] \delay_chain_qca[28] ;
  wire [7:0] \delay_chain_qca[29] ;
  wire [7:0] \delay_chain_qca[2] ;
  wire [7:0] \delay_chain_qca[30] ;
  wire [7:0] \delay_chain_qca[31] ;
  wire [7:0] \delay_chain_qca[32] ;
  wire [7:0] \delay_chain_qca[33] ;
  wire [7:0] \delay_chain_qca[34] ;
  wire [7:0] \delay_chain_qca[35] ;
  wire [7:0] \delay_chain_qca[36] ;
  wire [7:0] \delay_chain_qca[37] ;
  wire [7:0] \delay_chain_qca[38] ;
  wire [7:0] \delay_chain_qca[39] ;
  wire [7:0] \delay_chain_qca[3] ;
  wire [7:0] \delay_chain_qca[40] ;
  wire [7:0] \delay_chain_qca[41] ;
  wire [7:0] \delay_chain_qca[42] ;
  wire [7:0] \delay_chain_qca[43] ;
  wire [7:0] \delay_chain_qca[44] ;
  wire [7:0] \delay_chain_qca[45] ;
  wire [7:0] \delay_chain_qca[46] ;
  wire [7:0] \delay_chain_qca[47] ;
  wire [7:0] \delay_chain_qca[48] ;
  wire [7:0] \delay_chain_qca[49] ;
  wire [7:0] \delay_chain_qca[4] ;
  wire [7:0] \delay_chain_qca[50] ;
  wire [7:0] \delay_chain_qca[51] ;
  wire [7:0] \delay_chain_qca[52] ;
  wire [7:0] \delay_chain_qca[53] ;
  wire [7:0] \delay_chain_qca[54] ;
  wire [7:0] \delay_chain_qca[55] ;
  wire [7:0] \delay_chain_qca[5] ;
  wire [7:0] \delay_chain_qca[6] ;
  wire [7:0] \delay_chain_qca[7] ;
  wire [7:0] \delay_chain_qca[8] ;
  wire [7:0] \delay_chain_qca[9] ;
  wire [7:0] \delay_chain_qck[0] ;
  wire [7:0] \delay_chain_qck[1] ;
  wire [7:0] \delay_chain_qck[2] ;
  wire [7:0] \delay_chain_qck[3] ;
  wire [7:0] \delay_chain_qck[4] ;
  wire [7:0] \delay_chain_qck[5] ;
  wire [7:0] \delay_chain_qck[6] ;
  wire [7:0] \delay_chain_qck[7] ;
  input gate_enable;
  wire gate_enable;
  output [7:0] gate_status;
  wire [7:0] gate_status;
  wire [7:0] lock_counter;
  wire [7:0] phase_adjust;
  wire phase_locked;
  input power_down;
  wire power_down;
  wire [6:0] qca_delayed;
  wire [6:0] qca_gate;
  output qca_gated;
  wire qca_gated;
  input [6:0] qca_in;
  wire [6:0] qca_in;
  output [6:0] qca_out;
  wire [6:0] qca_out;
  wire qck_delayed;
  wire qck_gate;
  output qck_gated;
  wire qck_gated;
  input qck_in;
  wire qck_in;
  wire qck_n_gate;
  input qck_n_in;
  wire qck_n_in;
  output qck_n_out;
  wire qck_n_out;
  output qck_out;
  wire qck_out;
  input rst_n;
  wire rst_n;
  \$_DFF_P_  \delay_chain_qca_reg[12][0]  /* _176_ */ (
    .C(clk),
    .D(\delay_chain_qca[11] [0]),
    .Q(\delay_chain_qca[12] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[11][0]  /* _177_ */ (
    .C(clk),
    .D(\delay_chain_qca[10] [0]),
    .Q(\delay_chain_qca[11] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[10][0]  /* _178_ */ (
    .C(clk),
    .D(\delay_chain_qca[9] [0]),
    .Q(\delay_chain_qca[10] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[9][0]  /* _179_ */ (
    .C(clk),
    .D(\delay_chain_qca[8] [0]),
    .Q(\delay_chain_qca[9] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[0][0]  /* _180_ */ (
    .C(clk),
    .D(qck_gate),
    .Q(\delay_chain_qck[0] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[7][0]  /* _181_ */ (
    .C(clk),
    .D(\delay_chain_qca[6] [0]),
    .Q(\delay_chain_qca[7] [0])
  );
  \$_DFFE_PN0P_  \cal_counter_reg[0]  /* _182_ */ (
    .C(clk),
    .D(_000_[0]),
    .E(_004_),
    .Q(cal_counter[0]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[1]  /* _183_ */ (
    .C(clk),
    .D(_000_[1]),
    .E(_004_),
    .Q(cal_counter[1]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[2]  /* _184_ */ (
    .C(clk),
    .D(_000_[2]),
    .E(_004_),
    .Q(cal_counter[2]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[3]  /* _185_ */ (
    .C(clk),
    .D(_000_[3]),
    .E(_004_),
    .Q(cal_counter[3]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[4]  /* _186_ */ (
    .C(clk),
    .D(_000_[4]),
    .E(_004_),
    .Q(cal_counter[4]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[5]  /* _187_ */ (
    .C(clk),
    .D(_000_[5]),
    .E(_004_),
    .Q(cal_counter[5]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[6]  /* _188_ */ (
    .C(clk),
    .D(_000_[6]),
    .E(_004_),
    .Q(cal_counter[6]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[7]  /* _189_ */ (
    .C(clk),
    .D(_000_[7]),
    .E(_004_),
    .Q(cal_counter[7]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[8]  /* _190_ */ (
    .C(clk),
    .D(_000_[8]),
    .E(_004_),
    .Q(cal_counter[8]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[9]  /* _191_ */ (
    .C(clk),
    .D(_000_[9]),
    .E(_004_),
    .Q(cal_counter[9]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[10]  /* _192_ */ (
    .C(clk),
    .D(_000_[10]),
    .E(_004_),
    .Q(cal_counter[10]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[11]  /* _193_ */ (
    .C(clk),
    .D(_000_[11]),
    .E(_004_),
    .Q(cal_counter[11]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[12]  /* _194_ */ (
    .C(clk),
    .D(_000_[12]),
    .E(_004_),
    .Q(cal_counter[12]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[13]  /* _195_ */ (
    .C(clk),
    .D(_000_[13]),
    .E(_004_),
    .Q(cal_counter[13]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[14]  /* _196_ */ (
    .C(clk),
    .D(_000_[14]),
    .E(_004_),
    .Q(cal_counter[14]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \cal_counter_reg[15]  /* _197_ */ (
    .C(clk),
    .D(_000_[15]),
    .E(_004_),
    .Q(cal_counter[15]),
    .R(rst_n)
  );
  \$_DFF_P_  \delay_chain_qca_reg[5][0]  /* _198_ */ (
    .C(clk),
    .D(\delay_chain_qca[4] [0]),
    .Q(\delay_chain_qca[5] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[6][0]  /* _199_ */ (
    .C(clk),
    .D(\delay_chain_qca[5] [0]),
    .Q(\delay_chain_qca[6] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[4][0]  /* _200_ */ (
    .C(clk),
    .D(\delay_chain_qca[3] [0]),
    .Q(\delay_chain_qca[4] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[3][0]  /* _201_ */ (
    .C(clk),
    .D(\delay_chain_qca[2] [0]),
    .Q(\delay_chain_qca[3] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[2][0]  /* _202_ */ (
    .C(clk),
    .D(\delay_chain_qca[1] [0]),
    .Q(\delay_chain_qca[2] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[1][0]  /* _203_ */ (
    .C(clk),
    .D(\delay_chain_qca[0] [0]),
    .Q(\delay_chain_qca[1] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[48][0]  /* _204_ */ (
    .C(clk),
    .D(qca_gate[6]),
    .Q(\delay_chain_qca[48] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[1][0]  /* _205_ */ (
    .C(clk),
    .D(\delay_chain_qck[0] [0]),
    .Q(\delay_chain_qck[1] [0])
  );
  \$_DFF_PN0_  phase_locked_reg /* _206_ */ (
    .C(clk),
    .D(_003_),
    .Q(phase_locked),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[0]  /* _207_ */ (
    .C(clk),
    .D(_102_[0]),
    .E(_008_),
    .Q(lock_counter[0]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[1]  /* _208_ */ (
    .C(clk),
    .D(_102_[1]),
    .E(_008_),
    .Q(lock_counter[1]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[2]  /* _209_ */ (
    .C(clk),
    .D(_102_[2]),
    .E(_008_),
    .Q(lock_counter[2]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[3]  /* _210_ */ (
    .C(clk),
    .D(_102_[3]),
    .E(_008_),
    .Q(lock_counter[3]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[4]  /* _211_ */ (
    .C(clk),
    .D(_102_[4]),
    .E(_008_),
    .Q(lock_counter[4]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[5]  /* _212_ */ (
    .C(clk),
    .D(_102_[5]),
    .E(_008_),
    .Q(lock_counter[5]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[6]  /* _213_ */ (
    .C(clk),
    .D(_102_[6]),
    .E(_008_),
    .Q(lock_counter[6]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \lock_counter_reg[7]  /* _214_ */ (
    .C(clk),
    .D(_102_[7]),
    .E(_008_),
    .Q(lock_counter[7]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[0]  /* _215_ */ (
    .C(clk),
    .D(_117_[0]),
    .E(_007_),
    .Q(phase_adjust[0]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[1]  /* _216_ */ (
    .C(clk),
    .D(_009_),
    .E(_007_),
    .Q(phase_adjust[1]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[2]  /* _217_ */ (
    .C(clk),
    .D(_103_[2]),
    .E(_007_),
    .Q(phase_adjust[2]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[3]  /* _218_ */ (
    .C(clk),
    .D(_103_[3]),
    .E(_007_),
    .Q(phase_adjust[3]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[4]  /* _219_ */ (
    .C(clk),
    .D(_103_[4]),
    .E(_007_),
    .Q(phase_adjust[4]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[5]  /* _220_ */ (
    .C(clk),
    .D(_103_[5]),
    .E(_007_),
    .Q(phase_adjust[5]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[6]  /* _221_ */ (
    .C(clk),
    .D(_103_[6]),
    .E(_007_),
    .Q(phase_adjust[6]),
    .R(rst_n)
  );
  \$_DFFE_PN0P_  \phase_adjust_reg[7]  /* _222_ */ (
    .C(clk),
    .D(_103_[7]),
    .E(_007_),
    .Q(phase_adjust[7]),
    .R(rst_n)
  );
  \$_DFF_PN0_  calibration_active_reg /* _223_ */ (
    .C(clk),
    .D(_002_),
    .Q(calibration_active),
    .R(rst_n)
  );
  \$_DFF_PN0_  cal_done_reg /* _224_ */ (
    .C(clk),
    .D(_001_),
    .Q(cal_done),
    .R(rst_n)
  );
  \$_DFF_P_  \delay_chain_qck_reg[7][0]  /* _225_ */ (
    .C(clk),
    .D(\delay_chain_qck[6] [0]),
    .Q(\delay_chain_qck[7] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[6][0]  /* _226_ */ (
    .C(clk),
    .D(\delay_chain_qck[5] [0]),
    .Q(\delay_chain_qck[6] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[5][0]  /* _227_ */ (
    .C(clk),
    .D(\delay_chain_qck[4] [0]),
    .Q(\delay_chain_qck[5] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[4][0]  /* _228_ */ (
    .C(clk),
    .D(\delay_chain_qck[3] [0]),
    .Q(\delay_chain_qck[4] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[3][0]  /* _229_ */ (
    .C(clk),
    .D(\delay_chain_qck[2] [0]),
    .Q(\delay_chain_qck[3] [0])
  );
  \$_DFF_P_  \delay_chain_qck_reg[2][0]  /* _230_ */ (
    .C(clk),
    .D(\delay_chain_qck[1] [0]),
    .Q(\delay_chain_qck[2] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[40][0]  /* _231_ */ (
    .C(clk),
    .D(qca_gate[5]),
    .Q(\delay_chain_qca[40] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[55][0]  /* _232_ */ (
    .C(clk),
    .D(\delay_chain_qca[54] [0]),
    .Q(\delay_chain_qca[55] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[54][0]  /* _233_ */ (
    .C(clk),
    .D(\delay_chain_qca[53] [0]),
    .Q(\delay_chain_qca[54] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[53][0]  /* _234_ */ (
    .C(clk),
    .D(\delay_chain_qca[52] [0]),
    .Q(\delay_chain_qca[53] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[52][0]  /* _235_ */ (
    .C(clk),
    .D(\delay_chain_qca[51] [0]),
    .Q(\delay_chain_qca[52] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[51][0]  /* _236_ */ (
    .C(clk),
    .D(\delay_chain_qca[50] [0]),
    .Q(\delay_chain_qca[51] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[50][0]  /* _237_ */ (
    .C(clk),
    .D(\delay_chain_qca[49] [0]),
    .Q(\delay_chain_qca[50] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[49][0]  /* _238_ */ (
    .C(clk),
    .D(\delay_chain_qca[48] [0]),
    .Q(\delay_chain_qca[49] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[32][0]  /* _239_ */ (
    .C(clk),
    .D(qca_gate[4]),
    .Q(\delay_chain_qca[32] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[47][0]  /* _240_ */ (
    .C(clk),
    .D(\delay_chain_qca[46] [0]),
    .Q(\delay_chain_qca[47] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[46][0]  /* _241_ */ (
    .C(clk),
    .D(\delay_chain_qca[45] [0]),
    .Q(\delay_chain_qca[46] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[45][0]  /* _242_ */ (
    .C(clk),
    .D(\delay_chain_qca[44] [0]),
    .Q(\delay_chain_qca[45] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[44][0]  /* _243_ */ (
    .C(clk),
    .D(\delay_chain_qca[43] [0]),
    .Q(\delay_chain_qca[44] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[43][0]  /* _244_ */ (
    .C(clk),
    .D(\delay_chain_qca[42] [0]),
    .Q(\delay_chain_qca[43] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[42][0]  /* _245_ */ (
    .C(clk),
    .D(\delay_chain_qca[41] [0]),
    .Q(\delay_chain_qca[42] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[41][0]  /* _246_ */ (
    .C(clk),
    .D(\delay_chain_qca[40] [0]),
    .Q(\delay_chain_qca[41] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[24][0]  /* _247_ */ (
    .C(clk),
    .D(qca_gate[3]),
    .Q(\delay_chain_qca[24] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[39][0]  /* _248_ */ (
    .C(clk),
    .D(\delay_chain_qca[38] [0]),
    .Q(\delay_chain_qca[39] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[38][0]  /* _249_ */ (
    .C(clk),
    .D(\delay_chain_qca[37] [0]),
    .Q(\delay_chain_qca[38] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[37][0]  /* _250_ */ (
    .C(clk),
    .D(\delay_chain_qca[36] [0]),
    .Q(\delay_chain_qca[37] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[36][0]  /* _251_ */ (
    .C(clk),
    .D(\delay_chain_qca[35] [0]),
    .Q(\delay_chain_qca[36] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[35][0]  /* _252_ */ (
    .C(clk),
    .D(\delay_chain_qca[34] [0]),
    .Q(\delay_chain_qca[35] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[34][0]  /* _253_ */ (
    .C(clk),
    .D(\delay_chain_qca[33] [0]),
    .Q(\delay_chain_qca[34] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[33][0]  /* _254_ */ (
    .C(clk),
    .D(\delay_chain_qca[32] [0]),
    .Q(\delay_chain_qca[33] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[16][0]  /* _255_ */ (
    .C(clk),
    .D(qca_gate[2]),
    .Q(\delay_chain_qca[16] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[31][0]  /* _256_ */ (
    .C(clk),
    .D(\delay_chain_qca[30] [0]),
    .Q(\delay_chain_qca[31] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[30][0]  /* _257_ */ (
    .C(clk),
    .D(\delay_chain_qca[29] [0]),
    .Q(\delay_chain_qca[30] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[29][0]  /* _258_ */ (
    .C(clk),
    .D(\delay_chain_qca[28] [0]),
    .Q(\delay_chain_qca[29] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[28][0]  /* _259_ */ (
    .C(clk),
    .D(\delay_chain_qca[27] [0]),
    .Q(\delay_chain_qca[28] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[27][0]  /* _260_ */ (
    .C(clk),
    .D(\delay_chain_qca[26] [0]),
    .Q(\delay_chain_qca[27] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[26][0]  /* _261_ */ (
    .C(clk),
    .D(\delay_chain_qca[25] [0]),
    .Q(\delay_chain_qca[26] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[25][0]  /* _262_ */ (
    .C(clk),
    .D(\delay_chain_qca[24] [0]),
    .Q(\delay_chain_qca[25] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[8][0]  /* _263_ */ (
    .C(clk),
    .D(qca_gate[1]),
    .Q(\delay_chain_qca[8] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[23][0]  /* _264_ */ (
    .C(clk),
    .D(\delay_chain_qca[22] [0]),
    .Q(\delay_chain_qca[23] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[22][0]  /* _265_ */ (
    .C(clk),
    .D(\delay_chain_qca[21] [0]),
    .Q(\delay_chain_qca[22] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[21][0]  /* _266_ */ (
    .C(clk),
    .D(\delay_chain_qca[20] [0]),
    .Q(\delay_chain_qca[21] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[20][0]  /* _267_ */ (
    .C(clk),
    .D(\delay_chain_qca[19] [0]),
    .Q(\delay_chain_qca[20] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[19][0]  /* _268_ */ (
    .C(clk),
    .D(\delay_chain_qca[18] [0]),
    .Q(\delay_chain_qca[19] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[18][0]  /* _269_ */ (
    .C(clk),
    .D(\delay_chain_qca[17] [0]),
    .Q(\delay_chain_qca[18] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[17][0]  /* _270_ */ (
    .C(clk),
    .D(\delay_chain_qca[16] [0]),
    .Q(\delay_chain_qca[17] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[0][0]  /* _271_ */ (
    .C(clk),
    .D(qca_gate[0]),
    .Q(\delay_chain_qca[0] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[15][0]  /* _272_ */ (
    .C(clk),
    .D(\delay_chain_qca[14] [0]),
    .Q(\delay_chain_qca[15] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[14][0]  /* _273_ */ (
    .C(clk),
    .D(\delay_chain_qca[13] [0]),
    .Q(\delay_chain_qca[14] [0])
  );
  \$_DFF_P_  \delay_chain_qca_reg[13][0]  /* _274_ */ (
    .C(clk),
    .D(\delay_chain_qca[12] [0]),
    .Q(\delay_chain_qca[13] [0])
  );
  \$_NOT_  _275_ (
    .A(cal_counter[1]),
    .Y(_011_)
  );
  \$_NOT_  _276_ (
    .A(cal_counter[2]),
    .Y(_012_)
  );
  \$_NOT_  _277_ (
    .A(cal_counter[3]),
    .Y(_013_)
  );
  \$_NOT_  _278_ (
    .A(cal_counter[4]),
    .Y(_014_)
  );
  \$_NOT_  _279_ (
    .A(cal_counter[5]),
    .Y(_015_)
  );
  \$_NOT_  _280_ (
    .A(cal_counter[6]),
    .Y(_016_)
  );
  \$_NOT_  _281_ (
    .A(cal_counter[7]),
    .Y(_017_)
  );
  \$_NOT_  _282_ (
    .A(cal_counter[8]),
    .Y(_018_)
  );
  \$_NOT_  _283_ (
    .A(cal_counter[9]),
    .Y(_019_)
  );
  \$_NOT_  _284_ (
    .A(cal_counter[10]),
    .Y(_020_)
  );
  \$_NOT_  _285_ (
    .A(cal_counter[11]),
    .Y(_021_)
  );
  \$_NOT_  _286_ (
    .A(cal_counter[12]),
    .Y(_022_)
  );
  \$_NOT_  _287_ (
    .A(cal_counter[13]),
    .Y(_023_)
  );
  \$_NOT_  _288_ (
    .A(cal_counter[14]),
    .Y(_024_)
  );
  \$_NOT_  _289_ (
    .A(cal_counter[15]),
    .Y(_025_)
  );
  \$_NOT_  _290_ (
    .A(cal_counter[0]),
    .Y(_114_[0])
  );
  \$_NOT_  _291_ (
    .A(phase_adjust[0]),
    .Y(_117_[0])
  );
  \$_NOT_  _292_ (
    .A(phase_adjust[7]),
    .Y(_122_[7])
  );
  \$_NOT_  _293_ (
    .A(phase_adjust[6]),
    .Y(_122_[6])
  );
  \$_NOT_  _294_ (
    .A(phase_adjust[2]),
    .Y(_122_[2])
  );
  \$_NOT_  _295_ (
    .A(phase_adjust[3]),
    .Y(_122_[3])
  );
  \$_NOT_  _296_ (
    .A(lock_counter[0]),
    .Y(_120_[0])
  );
  \$_NOT_  _297_ (
    .A(lock_counter[2]),
    .Y(_128_[2])
  );
  \$mux  #(
    .WIDTH(32'd1)
  ) _298_ (
    .A(phase_adjust[1]),
    .B(_122_[1]),
    .S(_127_),
    .Y(_010_)
  );
  \$_OR_  _299_ (
    .A(_114_[0]),
    .B(_011_),
    .Y(_026_[0])
  );
  \$_OR_  _300_ (
    .A(_012_),
    .B(_013_),
    .Y(_026_[1])
  );
  \$_OR_  _301_ (
    .A(_014_),
    .B(_015_),
    .Y(_026_[2])
  );
  \$_OR_  _302_ (
    .A(_016_),
    .B(_017_),
    .Y(_026_[3])
  );
  \$_OR_  _303_ (
    .A(_018_),
    .B(_019_),
    .Y(_026_[4])
  );
  \$_OR_  _304_ (
    .A(_020_),
    .B(_021_),
    .Y(_026_[5])
  );
  \$_OR_  _305_ (
    .A(_022_),
    .B(_023_),
    .Y(_026_[6])
  );
  \$_OR_  _306_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_[7])
  );
  \$_OR_  _307_ (
    .A(_026_[0]),
    .B(_026_[1]),
    .Y(_027_[0])
  );
  \$_OR_  _308_ (
    .A(_026_[2]),
    .B(_026_[3]),
    .Y(_027_[1])
  );
  \$_OR_  _309_ (
    .A(_026_[4]),
    .B(_026_[5]),
    .Y(_027_[2])
  );
  \$_OR_  _310_ (
    .A(_026_[6]),
    .B(_026_[7]),
    .Y(_027_[3])
  );
  \$_OR_  _311_ (
    .A(_027_[0]),
    .B(_027_[1]),
    .Y(_028_[0])
  );
  \$_OR_  _312_ (
    .A(_027_[2]),
    .B(_027_[3]),
    .Y(_028_[1])
  );
  \$_OR_  _313_ (
    .A(_028_[0]),
    .B(_028_[1]),
    .Y(_057_)
  );
  \$_OR_  _314_ (
    .A(_094_[0]),
    .B(_094_[1]),
    .Y(_029_[0])
  );
  \$_OR_  _315_ (
    .A(_094_[2]),
    .B(_094_[3]),
    .Y(_029_[1])
  );
  \$_OR_  _316_ (
    .A(_094_[4]),
    .B(_094_[5]),
    .Y(_029_[2])
  );
  \$_OR_  _317_ (
    .A(_094_[6]),
    .B(_094_[7]),
    .Y(_029_[3])
  );
  \$_OR_  _318_ (
    .A(_029_[0]),
    .B(_029_[1]),
    .Y(_030_[0])
  );
  \$_OR_  _319_ (
    .A(_029_[2]),
    .B(_029_[3]),
    .Y(_030_[1])
  );
  \$_OR_  _320_ (
    .A(_030_[0]),
    .B(_030_[1]),
    .Y(qca_delayed[1])
  );
  \$_OR_  _321_ (
    .A(_095_[0]),
    .B(_095_[1]),
    .Y(_031_[0])
  );
  \$_OR_  _322_ (
    .A(_095_[2]),
    .B(_095_[3]),
    .Y(_031_[1])
  );
  \$_OR_  _323_ (
    .A(_095_[4]),
    .B(_095_[5]),
    .Y(_031_[2])
  );
  \$_OR_  _324_ (
    .A(_095_[6]),
    .B(_095_[7]),
    .Y(_031_[3])
  );
  \$_OR_  _325_ (
    .A(_031_[0]),
    .B(_031_[1]),
    .Y(_032_[0])
  );
  \$_OR_  _326_ (
    .A(_031_[2]),
    .B(_031_[3]),
    .Y(_032_[1])
  );
  \$_OR_  _327_ (
    .A(_032_[0]),
    .B(_032_[1]),
    .Y(qca_delayed[0])
  );
  \$_OR_  _328_ (
    .A(_096_[0]),
    .B(_096_[1]),
    .Y(_033_[0])
  );
  \$_OR_  _329_ (
    .A(_096_[2]),
    .B(_096_[3]),
    .Y(_033_[1])
  );
  \$_OR_  _330_ (
    .A(_096_[4]),
    .B(_096_[5]),
    .Y(_033_[2])
  );
  \$_OR_  _331_ (
    .A(_096_[6]),
    .B(_096_[7]),
    .Y(_033_[3])
  );
  \$_OR_  _332_ (
    .A(_033_[0]),
    .B(_033_[1]),
    .Y(_034_[0])
  );
  \$_OR_  _333_ (
    .A(_033_[2]),
    .B(_033_[3]),
    .Y(_034_[1])
  );
  \$_OR_  _334_ (
    .A(_034_[0]),
    .B(_034_[1]),
    .Y(qck_delayed)
  );
  \$_OR_  _335_ (
    .A(_093_[0]),
    .B(_093_[1]),
    .Y(_035_[0])
  );
  \$_OR_  _336_ (
    .A(_093_[2]),
    .B(_093_[3]),
    .Y(_035_[1])
  );
  \$_OR_  _337_ (
    .A(_093_[4]),
    .B(_093_[5]),
    .Y(_035_[2])
  );
  \$_OR_  _338_ (
    .A(_093_[6]),
    .B(_093_[7]),
    .Y(_035_[3])
  );
  \$_OR_  _339_ (
    .A(_035_[0]),
    .B(_035_[1]),
    .Y(_036_[0])
  );
  \$_OR_  _340_ (
    .A(_035_[2]),
    .B(_035_[3]),
    .Y(_036_[1])
  );
  \$_OR_  _341_ (
    .A(_036_[0]),
    .B(_036_[1]),
    .Y(qca_delayed[2])
  );
  \$_OR_  _342_ (
    .A(_092_[0]),
    .B(_092_[1]),
    .Y(_037_[0])
  );
  \$_OR_  _343_ (
    .A(_092_[2]),
    .B(_092_[3]),
    .Y(_037_[1])
  );
  \$_OR_  _344_ (
    .A(_092_[4]),
    .B(_092_[5]),
    .Y(_037_[2])
  );
  \$_OR_  _345_ (
    .A(_092_[6]),
    .B(_092_[7]),
    .Y(_037_[3])
  );
  \$_OR_  _346_ (
    .A(_037_[0]),
    .B(_037_[1]),
    .Y(_038_[0])
  );
  \$_OR_  _347_ (
    .A(_037_[2]),
    .B(_037_[3]),
    .Y(_038_[1])
  );
  \$_OR_  _348_ (
    .A(_038_[0]),
    .B(_038_[1]),
    .Y(qca_delayed[3])
  );
  \$_OR_  _349_ (
    .A(_091_[0]),
    .B(_091_[1]),
    .Y(_039_[0])
  );
  \$_OR_  _350_ (
    .A(_091_[2]),
    .B(_091_[3]),
    .Y(_039_[1])
  );
  \$_OR_  _351_ (
    .A(_091_[4]),
    .B(_091_[5]),
    .Y(_039_[2])
  );
  \$_OR_  _352_ (
    .A(_091_[6]),
    .B(_091_[7]),
    .Y(_039_[3])
  );
  \$_OR_  _353_ (
    .A(_039_[0]),
    .B(_039_[1]),
    .Y(_040_[0])
  );
  \$_OR_  _354_ (
    .A(_039_[2]),
    .B(_039_[3]),
    .Y(_040_[1])
  );
  \$_OR_  _355_ (
    .A(_040_[0]),
    .B(_040_[1]),
    .Y(qca_delayed[4])
  );
  \$_OR_  _356_ (
    .A(_090_[0]),
    .B(_090_[1]),
    .Y(_041_[0])
  );
  \$_OR_  _357_ (
    .A(_090_[2]),
    .B(_090_[3]),
    .Y(_041_[1])
  );
  \$_OR_  _358_ (
    .A(_090_[4]),
    .B(_090_[5]),
    .Y(_041_[2])
  );
  \$_OR_  _359_ (
    .A(_090_[6]),
    .B(_090_[7]),
    .Y(_041_[3])
  );
  \$_OR_  _360_ (
    .A(_041_[0]),
    .B(_041_[1]),
    .Y(_042_[0])
  );
  \$_OR_  _361_ (
    .A(_041_[2]),
    .B(_041_[3]),
    .Y(_042_[1])
  );
  \$_OR_  _362_ (
    .A(_042_[0]),
    .B(_042_[1]),
    .Y(qca_delayed[5])
  );
  \$_OR_  _363_ (
    .A(_088_[0]),
    .B(_088_[1]),
    .Y(_043_[0])
  );
  \$_OR_  _364_ (
    .A(_088_[2]),
    .B(_088_[3]),
    .Y(_043_[1])
  );
  \$_OR_  _365_ (
    .A(_088_[4]),
    .B(_088_[5]),
    .Y(_043_[2])
  );
  \$_OR_  _366_ (
    .A(_088_[6]),
    .B(_088_[7]),
    .Y(_043_[3])
  );
  \$_OR_  _367_ (
    .A(_043_[0]),
    .B(_043_[1]),
    .Y(_044_[0])
  );
  \$_OR_  _368_ (
    .A(_043_[2]),
    .B(_043_[3]),
    .Y(_044_[1])
  );
  \$_OR_  _369_ (
    .A(_044_[0]),
    .B(_044_[1]),
    .Y(qca_delayed[6])
  );
  \$_AND_  _370_ (
    .A(_124_[0]),
    .B(_124_[1]),
    .Y(_045_[0])
  );
  \$_AND_  _371_ (
    .A(_045_[0]),
    .B(_045_[1]),
    .Y(_046_[0])
  );
  \$_AND_  _372_ (
    .A(_045_[2]),
    .B(_045_[3]),
    .Y(_046_[1])
  );
  \$_AND_  _373_ (
    .A(_046_[0]),
    .B(_046_[1]),
    .Y(_126_)
  );
  \$_OR_  _374_ (
    .A(_085_),
    .B(_067_),
    .Y(_005_)
  );
  \$_OR_  _375_ (
    .A(_005_),
    .B(_086_),
    .Y(_006_)
  );
  \$_OR_  _376_ (
    .A(_049_),
    .B(phase_adjust[2]),
    .Y(_058_)
  );
  \$_OR_  _377_ (
    .A(_050_),
    .B(phase_adjust[2]),
    .Y(_059_)
  );
  \$_OR_  _378_ (
    .A(_051_),
    .B(phase_adjust[2]),
    .Y(_060_)
  );
  \$_OR_  _379_ (
    .A(phase_adjust[0]),
    .B(phase_adjust[1]),
    .Y(_052_)
  );
  \$_OR_  _380_ (
    .A(_052_),
    .B(_122_[2]),
    .Y(_061_)
  );
  \$_OR_  _381_ (
    .A(_117_[0]),
    .B(phase_adjust[1]),
    .Y(_049_)
  );
  \$_OR_  _382_ (
    .A(_049_),
    .B(_122_[2]),
    .Y(_062_)
  );
  \$_OR_  _383_ (
    .A(phase_adjust[0]),
    .B(_122_[1]),
    .Y(_050_)
  );
  \$_OR_  _384_ (
    .A(_050_),
    .B(_122_[2]),
    .Y(_063_)
  );
  \$_OR_  _385_ (
    .A(_117_[0]),
    .B(_122_[1]),
    .Y(_051_)
  );
  \$_OR_  _386_ (
    .A(_051_),
    .B(_122_[2]),
    .Y(_064_)
  );
  \$_AND_  _387_ (
    .A(_006_),
    .B(calibration_active),
    .Y(_008_)
  );
  \$_AND_  _388_ (
    .A(_005_),
    .B(calibration_active),
    .Y(_007_)
  );
  \$_OR_  _389_ (
    .A(calibration_active),
    .B(_068_),
    .Y(_004_)
  );
  \$_OR_  _390_ (
    .A(qca_gate[0]),
    .B(qca_gate[1]),
    .Y(_053_[0])
  );
  \$_OR_  _391_ (
    .A(qca_gate[2]),
    .B(qca_gate[3]),
    .Y(_053_[1])
  );
  \$_OR_  _392_ (
    .A(qca_gate[4]),
    .B(qca_gate[5]),
    .Y(_053_[2])
  );
  \$_OR_  _393_ (
    .A(_053_[0]),
    .B(_053_[1]),
    .Y(_054_[0])
  );
  \$_OR_  _394_ (
    .A(_053_[2]),
    .B(qca_gate[6]),
    .Y(_054_[1])
  );
  \$_OR_  _395_ (
    .A(_054_[0]),
    .B(_054_[1]),
    .Y(_055_)
  );
  \$_OR_  _396_ (
    .A(_052_),
    .B(phase_adjust[2]),
    .Y(_056_)
  );
  \$_NOT_  _397_ (
    .A(bcw_qck_enable[0]),
    .Y(_069_)
  );
  \$_NOT_  _398_ (
    .A(_055_),
    .Y(_066_)
  );
  \$_NOT_  _399_ (
    .A(bcw_qca_enable[0]),
    .Y(_070_)
  );
  \$_NOT_  _400_ (
    .A(bcw_qca_enable[1]),
    .Y(_071_)
  );
  \$_NOT_  _401_ (
    .A(bcw_qca_enable[2]),
    .Y(_072_)
  );
  \$_NOT_  _402_ (
    .A(bcw_qca_enable[3]),
    .Y(_073_)
  );
  \$_NOT_  _403_ (
    .A(bcw_qca_enable[4]),
    .Y(_074_)
  );
  \$_NOT_  _404_ (
    .A(bcw_qca_enable[5]),
    .Y(_075_)
  );
  \$_NOT_  _405_ (
    .A(bcw_qca_enable[6]),
    .Y(_076_)
  );
  \$_NOT_  _406_ (
    .A(_056_),
    .Y(_089_[7])
  );
  \$_NOT_  _407_ (
    .A(_058_),
    .Y(_089_[6])
  );
  \$_NOT_  _408_ (
    .A(_059_),
    .Y(_089_[5])
  );
  \$_NOT_  _409_ (
    .A(_060_),
    .Y(_089_[4])
  );
  \$_NOT_  _410_ (
    .A(_061_),
    .Y(_089_[3])
  );
  \$_NOT_  _411_ (
    .A(_062_),
    .Y(_089_[2])
  );
  \$_NOT_  _412_ (
    .A(_063_),
    .Y(_089_[1])
  );
  \$_NOT_  _413_ (
    .A(_064_),
    .Y(_089_[0])
  );
  \$_OR_  _414_ (
    .A(power_down),
    .B(_069_),
    .Y(_077_)
  );
  \$_AND_  _415_ (
    .A(cal_start),
    .B(cal_enable),
    .Y(_068_)
  );
  \$_AND_  _416_ (
    .A(_065_),
    .B(power_down),
    .Y(qck_gated)
  );
  \$_AND_  _417_ (
    .A(_066_),
    .B(power_down),
    .Y(qca_gated)
  );
  \$_OR_  _418_ (
    .A(power_down),
    .B(_070_),
    .Y(_078_)
  );
  \$_OR_  _419_ (
    .A(power_down),
    .B(_071_),
    .Y(_079_)
  );
  \$_OR_  _420_ (
    .A(power_down),
    .B(_072_),
    .Y(_080_)
  );
  \$_OR_  _421_ (
    .A(power_down),
    .B(_073_),
    .Y(_081_)
  );
  \$_OR_  _422_ (
    .A(power_down),
    .B(_074_),
    .Y(_082_)
  );
  \$_OR_  _423_ (
    .A(power_down),
    .B(_075_),
    .Y(_083_)
  );
  \$_OR_  _424_ (
    .A(power_down),
    .B(_076_),
    .Y(_084_)
  );
  \$_MUX_  _425_ (
    .A(qca_in[6]),
    .B(1'h0),
    .S(_084_),
    .Y(qca_gate[6])
  );
  \$_MUX_  _426_ (
    .A(qck_gate),
    .B(qck_delayed),
    .S(cal_enable),
    .Y(qck_out)
  );
  \$_MUX_  _427_ (
    .A(qck_n_gate),
    .B(_087_),
    .S(cal_enable),
    .Y(qck_n_out)
  );
  \$_MUX_  _428_ (
    .A(qca_gate[0]),
    .B(qca_delayed[0]),
    .S(cal_enable),
    .Y(qca_out[0])
  );
  \$_MUX_  _429_ (
    .A(qca_gate[1]),
    .B(qca_delayed[1]),
    .S(cal_enable),
    .Y(qca_out[1])
  );
  \$_MUX_  _430_ (
    .A(qca_gate[2]),
    .B(qca_delayed[2]),
    .S(cal_enable),
    .Y(qca_out[2])
  );
  \$_MUX_  _431_ (
    .A(qca_gate[3]),
    .B(qca_delayed[3]),
    .S(cal_enable),
    .Y(qca_out[3])
  );
  \$_MUX_  _432_ (
    .A(qca_gate[4]),
    .B(qca_delayed[4]),
    .S(cal_enable),
    .Y(qca_out[4])
  );
  \$_MUX_  _433_ (
    .A(qca_gate[5]),
    .B(qca_delayed[5]),
    .S(cal_enable),
    .Y(qca_out[5])
  );
  \$_MUX_  _434_ (
    .A(qca_gate[6]),
    .B(qca_delayed[6]),
    .S(cal_enable),
    .Y(qca_out[6])
  );
  \$_MUX_  _435_ (
    .A(qck_in),
    .B(1'h0),
    .S(_077_),
    .Y(qck_gate)
  );
  \$_MUX_  _436_ (
    .A(qck_n_in),
    .B(1'h0),
    .S(_077_),
    .Y(qck_n_gate)
  );
  \$_MUX_  _437_ (
    .A(_108_),
    .B(_112_),
    .S(calibration_active),
    .Y(_001_)
  );
  \$_MUX_  _438_ (
    .A(1'h1),
    .B(_111_),
    .S(_057_),
    .Y(_112_)
  );
  \$_MUX_  _439_ (
    .A(_108_),
    .B(_110_),
    .S(_127_),
    .Y(_111_)
  );
  \$_MUX_  _440_ (
    .A(_108_),
    .B(_109_),
    .S(_123_[7]),
    .Y(_110_)
  );
  \$_OR_  _441_ (
    .A(_108_),
    .B(_131_),
    .Y(_109_)
  );
  \$_MUX_  _442_ (
    .A(cal_done),
    .B(1'h0),
    .S(_068_),
    .Y(_108_)
  );
  \$_MUX_  _443_ (
    .A(_004_),
    .B(_107_),
    .S(calibration_active),
    .Y(_002_)
  );
  \$_AND_  _444_ (
    .A(_057_),
    .B(_106_),
    .Y(_107_)
  );
  \$_MUX_  _445_ (
    .A(_004_),
    .B(_105_),
    .S(_127_),
    .Y(_106_)
  );
  \$_MUX_  _446_ (
    .A(_004_),
    .B(_104_),
    .S(_123_[7]),
    .Y(_105_)
  );
  \$_MUX_  _447_ (
    .A(_004_),
    .B(1'h0),
    .S(_131_),
    .Y(_104_)
  );
  \$_AND_  _448_ (
    .A(calibration_active),
    .B(_114_[0]),
    .Y(_000_[0])
  );
  \$_AND_  _449_ (
    .A(calibration_active),
    .B(_115_[1]),
    .Y(_000_[1])
  );
  \$_AND_  _450_ (
    .A(calibration_active),
    .B(_115_[2]),
    .Y(_000_[2])
  );
  \$_AND_  _451_ (
    .A(calibration_active),
    .B(_115_[3]),
    .Y(_000_[3])
  );
  \$_AND_  _452_ (
    .A(calibration_active),
    .B(_115_[4]),
    .Y(_000_[4])
  );
  \$_AND_  _453_ (
    .A(calibration_active),
    .B(_115_[5]),
    .Y(_000_[5])
  );
  \$_AND_  _454_ (
    .A(calibration_active),
    .B(_115_[6]),
    .Y(_000_[6])
  );
  \$_AND_  _455_ (
    .A(calibration_active),
    .B(_115_[7]),
    .Y(_000_[7])
  );
  \$_AND_  _456_ (
    .A(calibration_active),
    .B(_115_[8]),
    .Y(_000_[8])
  );
  \$_AND_  _457_ (
    .A(calibration_active),
    .B(_115_[9]),
    .Y(_000_[9])
  );
  \$_AND_  _458_ (
    .A(calibration_active),
    .B(_115_[10]),
    .Y(_000_[10])
  );
  \$_AND_  _459_ (
    .A(calibration_active),
    .B(_115_[11]),
    .Y(_000_[11])
  );
  \$_AND_  _460_ (
    .A(calibration_active),
    .B(_115_[12]),
    .Y(_000_[12])
  );
  \$_AND_  _461_ (
    .A(calibration_active),
    .B(_115_[13]),
    .Y(_000_[13])
  );
  \$_AND_  _462_ (
    .A(calibration_active),
    .B(_115_[14]),
    .Y(_000_[14])
  );
  \$_AND_  _463_ (
    .A(calibration_active),
    .B(_115_[15]),
    .Y(_000_[15])
  );
  \$_MUX_  _464_ (
    .A(_118_[2]),
    .B(_133_[2]),
    .S(_127_),
    .Y(_103_[2])
  );
  \$_MUX_  _465_ (
    .A(_118_[3]),
    .B(_133_[3]),
    .S(_127_),
    .Y(_103_[3])
  );
  \$_MUX_  _466_ (
    .A(_118_[4]),
    .B(_133_[4]),
    .S(_127_),
    .Y(_103_[4])
  );
  \$_MUX_  _467_ (
    .A(_118_[5]),
    .B(_133_[5]),
    .S(_127_),
    .Y(_103_[5])
  );
  \$_MUX_  _468_ (
    .A(_118_[6]),
    .B(_133_[6]),
    .S(_127_),
    .Y(_103_[6])
  );
  \$_MUX_  _469_ (
    .A(_118_[7]),
    .B(_133_[7]),
    .S(_127_),
    .Y(_103_[7])
  );
  \$_AND_  _470_ (
    .A(_127_),
    .B(_101_[0]),
    .Y(_102_[0])
  );
  \$_AND_  _471_ (
    .A(_127_),
    .B(_101_[1]),
    .Y(_102_[1])
  );
  \$_AND_  _472_ (
    .A(_127_),
    .B(_101_[2]),
    .Y(_102_[2])
  );
  \$_AND_  _473_ (
    .A(_127_),
    .B(_101_[3]),
    .Y(_102_[3])
  );
  \$_AND_  _474_ (
    .A(_127_),
    .B(_101_[4]),
    .Y(_102_[4])
  );
  \$_AND_  _475_ (
    .A(_127_),
    .B(_101_[5]),
    .Y(_102_[5])
  );
  \$_AND_  _476_ (
    .A(_127_),
    .B(_101_[6]),
    .Y(_102_[6])
  );
  \$_AND_  _477_ (
    .A(_127_),
    .B(_101_[7]),
    .Y(_102_[7])
  );
  \$_AND_  _478_ (
    .A(_123_[7]),
    .B(_120_[0]),
    .Y(_101_[0])
  );
  \$_AND_  _479_ (
    .A(_123_[7]),
    .B(_121_[1]),
    .Y(_101_[1])
  );
  \$_AND_  _480_ (
    .A(_123_[7]),
    .B(_121_[2]),
    .Y(_101_[2])
  );
  \$_AND_  _481_ (
    .A(_123_[7]),
    .B(_121_[3]),
    .Y(_101_[3])
  );
  \$_AND_  _482_ (
    .A(_123_[7]),
    .B(_121_[4]),
    .Y(_101_[4])
  );
  \$_AND_  _483_ (
    .A(_123_[7]),
    .B(_121_[5]),
    .Y(_101_[5])
  );
  \$_AND_  _484_ (
    .A(_123_[7]),
    .B(_121_[6]),
    .Y(_101_[6])
  );
  \$_AND_  _485_ (
    .A(_123_[7]),
    .B(_121_[7]),
    .Y(_101_[7])
  );
  \$_MUX_  _486_ (
    .A(_097_),
    .B(_100_),
    .S(calibration_active),
    .Y(_003_)
  );
  \$_MUX_  _487_ (
    .A(_097_),
    .B(_099_),
    .S(_127_),
    .Y(_100_)
  );
  \$_MUX_  _488_ (
    .A(_097_),
    .B(_098_),
    .S(_123_[7]),
    .Y(_099_)
  );
  \$_OR_  _489_ (
    .A(_097_),
    .B(_131_),
    .Y(_098_)
  );
  \$_MUX_  _490_ (
    .A(phase_locked),
    .B(1'h0),
    .S(_068_),
    .Y(_097_)
  );
  \$_MUX_  _491_ (
    .A(qca_in[0]),
    .B(1'h0),
    .S(_078_),
    .Y(qca_gate[0])
  );
  \$_MUX_  _492_ (
    .A(qca_in[1]),
    .B(1'h0),
    .S(_079_),
    .Y(qca_gate[1])
  );
  \$_MUX_  _493_ (
    .A(qca_in[2]),
    .B(1'h0),
    .S(_080_),
    .Y(qca_gate[2])
  );
  \$_MUX_  _494_ (
    .A(qca_in[3]),
    .B(1'h0),
    .S(_081_),
    .Y(qca_gate[3])
  );
  \$_MUX_  _495_ (
    .A(qca_in[4]),
    .B(1'h0),
    .S(_082_),
    .Y(qca_gate[4])
  );
  \$_MUX_  _496_ (
    .A(qca_in[5]),
    .B(1'h0),
    .S(_083_),
    .Y(qca_gate[5])
  );
  \$_NOT_  _497_ (
    .A(qck_delayed),
    .Y(_087_)
  );
  \$_NOT_  _498_ (
    .A(qck_gate),
    .Y(_065_)
  );
  \$_NOT_  _499_ (
    .A(_123_[7]),
    .Y(_067_)
  );
  \$_NOT_  _500_ (
    .A(_127_),
    .Y(_085_)
  );
  \$_NOT_  _501_ (
    .A(_129_[7]),
    .Y(_130_)
  );
  \$_NOT_  _502_ (
    .A(_131_),
    .Y(_086_)
  );
  \$_NOT_  _503_ (
    .A(phase_adjust[4]),
    .Y(_122_[4])
  );
  \$_NOT_  _504_ (
    .A(phase_adjust[5]),
    .Y(_122_[5])
  );
  \$_NOT_  _505_ (
    .A(phase_adjust[1]),
    .Y(_122_[1])
  );
  \$_NOT_  _506_ (
    .A(lock_counter[3]),
    .Y(_128_[3])
  );
  \$_NOT_  _507_ (
    .A(lock_counter[4]),
    .Y(_128_[4])
  );
  \$_NOT_  _508_ (
    .A(lock_counter[5]),
    .Y(_128_[5])
  );
  \$_NOT_  _509_ (
    .A(lock_counter[6]),
    .Y(_128_[6])
  );
  \$_NOT_  _510_ (
    .A(lock_counter[7]),
    .Y(_128_[7])
  );
  \$_AND_  _511_ (
    .A(\delay_chain_qca[15] [0]),
    .B(_089_[0]),
    .Y(_094_[0])
  );
  \$_AND_  _512_ (
    .A(\delay_chain_qca[14] [0]),
    .B(_089_[1]),
    .Y(_094_[1])
  );
  \$_AND_  _513_ (
    .A(\delay_chain_qca[13] [0]),
    .B(_089_[2]),
    .Y(_094_[2])
  );
  \$_AND_  _514_ (
    .A(\delay_chain_qca[12] [0]),
    .B(_089_[3]),
    .Y(_094_[3])
  );
  \$_AND_  _515_ (
    .A(\delay_chain_qca[11] [0]),
    .B(_089_[4]),
    .Y(_094_[4])
  );
  \$_AND_  _516_ (
    .A(\delay_chain_qca[10] [0]),
    .B(_089_[5]),
    .Y(_094_[5])
  );
  \$_AND_  _517_ (
    .A(\delay_chain_qca[9] [0]),
    .B(_089_[6]),
    .Y(_094_[6])
  );
  \$_AND_  _518_ (
    .A(\delay_chain_qca[8] [0]),
    .B(_089_[7]),
    .Y(_094_[7])
  );
  \$_AND_  _519_ (
    .A(\delay_chain_qca[7] [0]),
    .B(_089_[0]),
    .Y(_095_[0])
  );
  \$_AND_  _520_ (
    .A(\delay_chain_qca[6] [0]),
    .B(_089_[1]),
    .Y(_095_[1])
  );
  \$_AND_  _521_ (
    .A(\delay_chain_qca[5] [0]),
    .B(_089_[2]),
    .Y(_095_[2])
  );
  \$_AND_  _522_ (
    .A(\delay_chain_qca[4] [0]),
    .B(_089_[3]),
    .Y(_095_[3])
  );
  \$_AND_  _523_ (
    .A(\delay_chain_qca[3] [0]),
    .B(_089_[4]),
    .Y(_095_[4])
  );
  \$_AND_  _524_ (
    .A(\delay_chain_qca[2] [0]),
    .B(_089_[5]),
    .Y(_095_[5])
  );
  \$_AND_  _525_ (
    .A(\delay_chain_qca[1] [0]),
    .B(_089_[6]),
    .Y(_095_[6])
  );
  \$_AND_  _526_ (
    .A(\delay_chain_qca[0] [0]),
    .B(_089_[7]),
    .Y(_095_[7])
  );
  \$_AND_  _527_ (
    .A(\delay_chain_qck[7] [0]),
    .B(_089_[0]),
    .Y(_096_[0])
  );
  \$_AND_  _528_ (
    .A(\delay_chain_qck[6] [0]),
    .B(_089_[1]),
    .Y(_096_[1])
  );
  \$_AND_  _529_ (
    .A(\delay_chain_qck[5] [0]),
    .B(_089_[2]),
    .Y(_096_[2])
  );
  \$_AND_  _530_ (
    .A(\delay_chain_qck[4] [0]),
    .B(_089_[3]),
    .Y(_096_[3])
  );
  \$_AND_  _531_ (
    .A(\delay_chain_qck[3] [0]),
    .B(_089_[4]),
    .Y(_096_[4])
  );
  \$_AND_  _532_ (
    .A(\delay_chain_qck[2] [0]),
    .B(_089_[5]),
    .Y(_096_[5])
  );
  \$_AND_  _533_ (
    .A(\delay_chain_qck[1] [0]),
    .B(_089_[6]),
    .Y(_096_[6])
  );
  \$_AND_  _534_ (
    .A(\delay_chain_qck[0] [0]),
    .B(_089_[7]),
    .Y(_096_[7])
  );
  \$_AND_  _535_ (
    .A(\delay_chain_qca[16] [0]),
    .B(_089_[7]),
    .Y(_093_[7])
  );
  \$_AND_  _536_ (
    .A(\delay_chain_qca[17] [0]),
    .B(_089_[6]),
    .Y(_093_[6])
  );
  \$_AND_  _537_ (
    .A(\delay_chain_qca[18] [0]),
    .B(_089_[5]),
    .Y(_093_[5])
  );
  \$_AND_  _538_ (
    .A(\delay_chain_qca[19] [0]),
    .B(_089_[4]),
    .Y(_093_[4])
  );
  \$_AND_  _539_ (
    .A(\delay_chain_qca[20] [0]),
    .B(_089_[3]),
    .Y(_093_[3])
  );
  \$_AND_  _540_ (
    .A(\delay_chain_qca[21] [0]),
    .B(_089_[2]),
    .Y(_093_[2])
  );
  \$_AND_  _541_ (
    .A(\delay_chain_qca[22] [0]),
    .B(_089_[1]),
    .Y(_093_[1])
  );
  \$_AND_  _542_ (
    .A(\delay_chain_qca[23] [0]),
    .B(_089_[0]),
    .Y(_093_[0])
  );
  \$_AND_  _543_ (
    .A(\delay_chain_qca[24] [0]),
    .B(_089_[7]),
    .Y(_092_[7])
  );
  \$_AND_  _544_ (
    .A(\delay_chain_qca[25] [0]),
    .B(_089_[6]),
    .Y(_092_[6])
  );
  \$_AND_  _545_ (
    .A(\delay_chain_qca[26] [0]),
    .B(_089_[5]),
    .Y(_092_[5])
  );
  \$_AND_  _546_ (
    .A(\delay_chain_qca[27] [0]),
    .B(_089_[4]),
    .Y(_092_[4])
  );
  \$_AND_  _547_ (
    .A(\delay_chain_qca[28] [0]),
    .B(_089_[3]),
    .Y(_092_[3])
  );
  \$_AND_  _548_ (
    .A(\delay_chain_qca[29] [0]),
    .B(_089_[2]),
    .Y(_092_[2])
  );
  \$_AND_  _549_ (
    .A(\delay_chain_qca[30] [0]),
    .B(_089_[1]),
    .Y(_092_[1])
  );
  \$_AND_  _550_ (
    .A(\delay_chain_qca[31] [0]),
    .B(_089_[0]),
    .Y(_092_[0])
  );
  \$_AND_  _551_ (
    .A(\delay_chain_qca[32] [0]),
    .B(_089_[7]),
    .Y(_091_[7])
  );
  \$_AND_  _552_ (
    .A(\delay_chain_qca[33] [0]),
    .B(_089_[6]),
    .Y(_091_[6])
  );
  \$_AND_  _553_ (
    .A(\delay_chain_qca[34] [0]),
    .B(_089_[5]),
    .Y(_091_[5])
  );
  \$_AND_  _554_ (
    .A(\delay_chain_qca[35] [0]),
    .B(_089_[4]),
    .Y(_091_[4])
  );
  \$_AND_  _555_ (
    .A(\delay_chain_qca[36] [0]),
    .B(_089_[3]),
    .Y(_091_[3])
  );
  \$_AND_  _556_ (
    .A(\delay_chain_qca[37] [0]),
    .B(_089_[2]),
    .Y(_091_[2])
  );
  \$_AND_  _557_ (
    .A(\delay_chain_qca[38] [0]),
    .B(_089_[1]),
    .Y(_091_[1])
  );
  \$_AND_  _558_ (
    .A(\delay_chain_qca[39] [0]),
    .B(_089_[0]),
    .Y(_091_[0])
  );
  \$_AND_  _559_ (
    .A(\delay_chain_qca[40] [0]),
    .B(_089_[7]),
    .Y(_090_[7])
  );
  \$_AND_  _560_ (
    .A(\delay_chain_qca[41] [0]),
    .B(_089_[6]),
    .Y(_090_[6])
  );
  \$_AND_  _561_ (
    .A(\delay_chain_qca[42] [0]),
    .B(_089_[5]),
    .Y(_090_[5])
  );
  \$_AND_  _562_ (
    .A(\delay_chain_qca[43] [0]),
    .B(_089_[4]),
    .Y(_090_[4])
  );
  \$_AND_  _563_ (
    .A(\delay_chain_qca[44] [0]),
    .B(_089_[3]),
    .Y(_090_[3])
  );
  \$_AND_  _564_ (
    .A(\delay_chain_qca[45] [0]),
    .B(_089_[2]),
    .Y(_090_[2])
  );
  \$_AND_  _565_ (
    .A(\delay_chain_qca[46] [0]),
    .B(_089_[1]),
    .Y(_090_[1])
  );
  \$_AND_  _566_ (
    .A(\delay_chain_qca[47] [0]),
    .B(_089_[0]),
    .Y(_090_[0])
  );
  \$_AND_  _567_ (
    .A(\delay_chain_qca[48] [0]),
    .B(_089_[7]),
    .Y(_088_[7])
  );
  \$_AND_  _568_ (
    .A(\delay_chain_qca[49] [0]),
    .B(_089_[6]),
    .Y(_088_[6])
  );
  \$_AND_  _569_ (
    .A(\delay_chain_qca[50] [0]),
    .B(_089_[5]),
    .Y(_088_[5])
  );
  \$_AND_  _570_ (
    .A(\delay_chain_qca[51] [0]),
    .B(_089_[4]),
    .Y(_088_[4])
  );
  \$_AND_  _571_ (
    .A(\delay_chain_qca[52] [0]),
    .B(_089_[3]),
    .Y(_088_[3])
  );
  \$_AND_  _572_ (
    .A(\delay_chain_qca[53] [0]),
    .B(_089_[2]),
    .Y(_088_[2])
  );
  \$_AND_  _573_ (
    .A(\delay_chain_qca[54] [0]),
    .B(_089_[1]),
    .Y(_088_[1])
  );
  \$_AND_  _574_ (
    .A(\delay_chain_qca[55] [0]),
    .B(_089_[0]),
    .Y(_088_[0])
  );
  \$_OR_  _575_ (
    .A(_067_),
    .B(_126_),
    .Y(_127_)
  );
  \$_OR_  _576_ (
    .A(_130_),
    .B(_119_[7]),
    .Y(_131_)
  );
  \$_XOR_  _577_ (
    .A(cal_counter[1]),
    .B(cal_counter[0]),
    .Y(_115_[1])
  );
  \$_XOR_  _578_ (
    .A(cal_counter[2]),
    .B(_113_[1]),
    .Y(_115_[2])
  );
  \$_XOR_  _579_ (
    .A(cal_counter[3]),
    .B(_113_[2]),
    .Y(_115_[3])
  );
  \$_XOR_  _580_ (
    .A(cal_counter[4]),
    .B(_113_[3]),
    .Y(_115_[4])
  );
  \$_XOR_  _581_ (
    .A(cal_counter[5]),
    .B(_113_[4]),
    .Y(_115_[5])
  );
  \$_XOR_  _582_ (
    .A(cal_counter[6]),
    .B(_113_[5]),
    .Y(_115_[6])
  );
  \$_XOR_  _583_ (
    .A(cal_counter[7]),
    .B(_113_[6]),
    .Y(_115_[7])
  );
  \$_XOR_  _584_ (
    .A(cal_counter[8]),
    .B(_113_[7]),
    .Y(_115_[8])
  );
  \$_XOR_  _585_ (
    .A(cal_counter[9]),
    .B(_113_[8]),
    .Y(_115_[9])
  );
  \$_XOR_  _586_ (
    .A(cal_counter[10]),
    .B(_113_[9]),
    .Y(_115_[10])
  );
  \$_XOR_  _587_ (
    .A(cal_counter[11]),
    .B(_113_[10]),
    .Y(_115_[11])
  );
  \$_XOR_  _588_ (
    .A(cal_counter[12]),
    .B(_113_[11]),
    .Y(_115_[12])
  );
  \$_XOR_  _589_ (
    .A(cal_counter[13]),
    .B(_113_[12]),
    .Y(_115_[13])
  );
  \$_XOR_  _590_ (
    .A(cal_counter[14]),
    .B(_113_[13]),
    .Y(_115_[14])
  );
  \$_XOR_  _591_ (
    .A(cal_counter[15]),
    .B(_113_[14]),
    .Y(_115_[15])
  );
  \$_XOR_  _592_ (
    .A(cal_target_phase[2]),
    .B(_122_[2]),
    .Y(_124_[2])
  );
  \$_XOR_  _593_ (
    .A(cal_target_phase[4]),
    .B(_122_[4]),
    .Y(_124_[4])
  );
  \$_XOR_  _594_ (
    .A(cal_target_phase[5]),
    .B(_122_[5]),
    .Y(_124_[5])
  );
  \$_AND_  _595_ (
    .A(cal_target_phase[2]),
    .B(_122_[2]),
    .Y(_125_[2])
  );
  \$_AND_  _596_ (
    .A(cal_target_phase[5]),
    .B(_122_[5]),
    .Y(_125_[5])
  );
  \$_AND_  _597_ (
    .A(cal_target_phase[6]),
    .B(_122_[6]),
    .Y(_125_[6])
  );
  \$_XOR_  _598_ (
    .A(phase_adjust[2]),
    .B(_116_[1]),
    .Y(_118_[2])
  );
  \$_XOR_  _599_ (
    .A(phase_adjust[3]),
    .B(_116_[2]),
    .Y(_118_[3])
  );
  \$_XOR_  _600_ (
    .A(phase_adjust[4]),
    .B(_116_[3]),
    .Y(_118_[4])
  );
  \$_XOR_  _601_ (
    .A(phase_adjust[5]),
    .B(_116_[4]),
    .Y(_118_[5])
  );
  \$_XOR_  _602_ (
    .A(phase_adjust[6]),
    .B(_116_[5]),
    .Y(_118_[6])
  );
  \$_XOR_  _603_ (
    .A(phase_adjust[7]),
    .B(_116_[6]),
    .Y(_118_[7])
  );
  \$_XOR_  _604_ (
    .A(cal_target_phase[0]),
    .B(_117_[0]),
    .Y(_124_[0])
  );
  \$_XOR_  _605_ (
    .A(cal_target_phase[1]),
    .B(_122_[1]),
    .Y(_124_[1])
  );
  \$_XOR_  _606_ (
    .A(cal_target_phase[3]),
    .B(_122_[3]),
    .Y(_124_[3])
  );
  \$_XOR_  _607_ (
    .A(cal_target_phase[6]),
    .B(_122_[6]),
    .Y(_124_[6])
  );
  \$_XOR_  _608_ (
    .A(cal_target_phase[7]),
    .B(_122_[7]),
    .Y(_124_[7])
  );
  \$_AND_  _609_ (
    .A(cal_target_phase[0]),
    .B(_117_[0]),
    .Y(_125_[0])
  );
  \$_AND_  _610_ (
    .A(cal_target_phase[1]),
    .B(_122_[1]),
    .Y(_125_[1])
  );
  \$_AND_  _611_ (
    .A(cal_target_phase[3]),
    .B(_122_[3]),
    .Y(_125_[3])
  );
  \$_AND_  _612_ (
    .A(cal_target_phase[4]),
    .B(_122_[4]),
    .Y(_125_[4])
  );
  \$_AND_  _613_ (
    .A(cal_target_phase[7]),
    .B(_122_[7]),
    .Y(_125_[7])
  );
  \$_XOR_  _614_ (
    .A(_010_),
    .B(phase_adjust[0]),
    .Y(_009_)
  );
  \$_XOR_  _615_ (
    .A(_122_[2]),
    .B(_132_[1]),
    .Y(_133_[2])
  );
  \$_XOR_  _616_ (
    .A(_122_[3]),
    .B(_132_[2]),
    .Y(_133_[3])
  );
  \$_XOR_  _617_ (
    .A(_122_[4]),
    .B(_132_[3]),
    .Y(_133_[4])
  );
  \$_XOR_  _618_ (
    .A(_122_[5]),
    .B(_132_[4]),
    .Y(_133_[5])
  );
  \$_XOR_  _619_ (
    .A(_122_[6]),
    .B(_132_[5]),
    .Y(_133_[6])
  );
  \$_XOR_  _620_ (
    .A(_122_[7]),
    .B(_132_[6]),
    .Y(_133_[7])
  );
  \$_XOR_  _621_ (
    .A(lock_counter[1]),
    .B(lock_counter[0]),
    .Y(_121_[1])
  );
  \$_XOR_  _622_ (
    .A(lock_counter[2]),
    .B(_119_[1]),
    .Y(_121_[2])
  );
  \$_XOR_  _623_ (
    .A(lock_counter[3]),
    .B(_119_[2]),
    .Y(_121_[3])
  );
  \$_XOR_  _624_ (
    .A(lock_counter[4]),
    .B(_119_[3]),
    .Y(_121_[4])
  );
  \$_XOR_  _625_ (
    .A(lock_counter[5]),
    .B(_119_[4]),
    .Y(_121_[5])
  );
  \$_XOR_  _626_ (
    .A(lock_counter[6]),
    .B(_119_[5]),
    .Y(_121_[6])
  );
  \$_XOR_  _627_ (
    .A(lock_counter[7]),
    .B(_119_[6]),
    .Y(_121_[7])
  );
  \$_AND_  _628_ (
    .A(cal_counter[1]),
    .B(cal_counter[0]),
    .Y(_113_[1])
  );
  \$_AND_  _629_ (
    .A(_134_),
    .B(_113_[1]),
    .Y(_113_[3])
  );
  \$_AND_  _630_ (
    .A(_140_),
    .B(_113_[3]),
    .Y(_113_[7])
  );
  \$_AND_  _631_ (
    .A(cal_counter[3]),
    .B(cal_counter[2]),
    .Y(_134_)
  );
  \$_AND_  _632_ (
    .A(cal_counter[5]),
    .B(cal_counter[4]),
    .Y(_135_)
  );
  \$_AND_  _633_ (
    .A(cal_counter[7]),
    .B(cal_counter[6]),
    .Y(_136_)
  );
  \$_AND_  _634_ (
    .A(cal_counter[9]),
    .B(cal_counter[8]),
    .Y(_137_)
  );
  \$_AND_  _635_ (
    .A(cal_counter[11]),
    .B(cal_counter[10]),
    .Y(_138_)
  );
  \$_AND_  _636_ (
    .A(cal_counter[13]),
    .B(cal_counter[12]),
    .Y(_139_)
  );
  \$_AND_  _637_ (
    .A(_136_),
    .B(_135_),
    .Y(_140_)
  );
  \$_AND_  _638_ (
    .A(_138_),
    .B(_137_),
    .Y(_141_)
  );
  \$_AND_  _639_ (
    .A(_141_),
    .B(_113_[7]),
    .Y(_113_[11])
  );
  \$_AND_  _640_ (
    .A(_135_),
    .B(_113_[3]),
    .Y(_113_[5])
  );
  \$_AND_  _641_ (
    .A(_137_),
    .B(_113_[7]),
    .Y(_113_[9])
  );
  \$_AND_  _642_ (
    .A(_139_),
    .B(_113_[11]),
    .Y(_113_[13])
  );
  \$_AND_  _643_ (
    .A(cal_counter[2]),
    .B(_113_[1]),
    .Y(_113_[2])
  );
  \$_AND_  _644_ (
    .A(cal_counter[4]),
    .B(_113_[3]),
    .Y(_113_[4])
  );
  \$_AND_  _645_ (
    .A(cal_counter[6]),
    .B(_113_[5]),
    .Y(_113_[6])
  );
  \$_AND_  _646_ (
    .A(cal_counter[8]),
    .B(_113_[7]),
    .Y(_113_[8])
  );
  \$_AND_  _647_ (
    .A(cal_counter[10]),
    .B(_113_[9]),
    .Y(_113_[10])
  );
  \$_AND_  _648_ (
    .A(cal_counter[12]),
    .B(_113_[11]),
    .Y(_113_[12])
  );
  \$_AND_  _649_ (
    .A(cal_counter[14]),
    .B(_113_[13]),
    .Y(_113_[14])
  );
  \$_AND_  _650_ (
    .A(_124_[1]),
    .B(_123_[0]),
    .Y(_144_)
  );
  \$_AND_  _651_ (
    .A(_124_[5]),
    .B(_125_[4]),
    .Y(_146_)
  );
  \$_AND_  _652_ (
    .A(_124_[7]),
    .B(_125_[6]),
    .Y(_147_)
  );
  \$_AND_  _653_ (
    .A(_124_[3]),
    .B(_124_[2]),
    .Y(_045_[1])
  );
  \$_AND_  _654_ (
    .A(_124_[5]),
    .B(_124_[4]),
    .Y(_045_[2])
  );
  \$_OR_  _655_ (
    .A(_125_[0]),
    .B(_124_[0]),
    .Y(_123_[0])
  );
  \$_OR_  _656_ (
    .A(_125_[1]),
    .B(_144_),
    .Y(_123_[1])
  );
  \$_OR_  _657_ (
    .A(_125_[3]),
    .B(_145_),
    .Y(_151_)
  );
  \$_OR_  _658_ (
    .A(_125_[7]),
    .B(_147_),
    .Y(_153_)
  );
  \$_OR_  _659_ (
    .A(_154_),
    .B(_150_),
    .Y(_123_[7])
  );
  \$_AND_  _660_ (
    .A(phase_adjust[1]),
    .B(phase_adjust[0]),
    .Y(_116_[1])
  );
  \$_AND_  _661_ (
    .A(_142_),
    .B(_116_[1]),
    .Y(_116_[3])
  );
  \$_AND_  _662_ (
    .A(phase_adjust[3]),
    .B(phase_adjust[2]),
    .Y(_142_)
  );
  \$_AND_  _663_ (
    .A(phase_adjust[5]),
    .B(phase_adjust[4]),
    .Y(_143_)
  );
  \$_AND_  _664_ (
    .A(_143_),
    .B(_116_[3]),
    .Y(_116_[5])
  );
  \$_AND_  _665_ (
    .A(phase_adjust[2]),
    .B(_116_[1]),
    .Y(_116_[2])
  );
  \$_AND_  _666_ (
    .A(phase_adjust[4]),
    .B(_116_[3]),
    .Y(_116_[4])
  );
  \$_AND_  _667_ (
    .A(phase_adjust[6]),
    .B(_116_[5]),
    .Y(_116_[6])
  );
  \$_AND_  _668_ (
    .A(_124_[3]),
    .B(_125_[2]),
    .Y(_145_)
  );
  \$_AND_  _669_ (
    .A(_045_[1]),
    .B(_123_[1]),
    .Y(_148_)
  );
  \$_AND_  _670_ (
    .A(_045_[3]),
    .B(_152_),
    .Y(_149_)
  );
  \$_AND_  _671_ (
    .A(_046_[1]),
    .B(_123_[3]),
    .Y(_150_)
  );
  \$_AND_  _672_ (
    .A(_124_[7]),
    .B(_124_[6]),
    .Y(_045_[3])
  );
  \$_OR_  _673_ (
    .A(_125_[5]),
    .B(_146_),
    .Y(_152_)
  );
  \$_OR_  _674_ (
    .A(_151_),
    .B(_148_),
    .Y(_123_[3])
  );
  \$_OR_  _675_ (
    .A(_153_),
    .B(_149_),
    .Y(_154_)
  );
  \$_AND_  _676_ (
    .A(_122_[1]),
    .B(phase_adjust[0]),
    .Y(_164_)
  );
  \$_AND_  _677_ (
    .A(_122_[3]),
    .B(phase_adjust[2]),
    .Y(_165_)
  );
  \$_AND_  _678_ (
    .A(_122_[5]),
    .B(phase_adjust[4]),
    .Y(_166_)
  );
  \$_AND_  _679_ (
    .A(_168_),
    .B(_132_[1]),
    .Y(_167_)
  );
  \$_AND_  _680_ (
    .A(_122_[3]),
    .B(_122_[2]),
    .Y(_168_)
  );
  \$_AND_  _681_ (
    .A(_122_[5]),
    .B(_122_[4]),
    .Y(_169_)
  );
  \$_AND_  _682_ (
    .A(_169_),
    .B(_132_[3]),
    .Y(_170_)
  );
  \$_AND_  _683_ (
    .A(_122_[2]),
    .B(_132_[1]),
    .Y(_171_)
  );
  \$_AND_  _684_ (
    .A(_122_[4]),
    .B(_132_[3]),
    .Y(_172_)
  );
  \$_AND_  _685_ (
    .A(_122_[6]),
    .B(_132_[5]),
    .Y(_173_)
  );
  \$_OR_  _686_ (
    .A(phase_adjust[1]),
    .B(_164_),
    .Y(_132_[1])
  );
  \$_OR_  _687_ (
    .A(phase_adjust[3]),
    .B(_165_),
    .Y(_174_)
  );
  \$_OR_  _688_ (
    .A(phase_adjust[5]),
    .B(_166_),
    .Y(_175_)
  );
  \$_OR_  _689_ (
    .A(_174_),
    .B(_167_),
    .Y(_132_[3])
  );
  \$_OR_  _690_ (
    .A(_175_),
    .B(_170_),
    .Y(_132_[5])
  );
  \$_OR_  _691_ (
    .A(phase_adjust[2]),
    .B(_171_),
    .Y(_132_[2])
  );
  \$_OR_  _692_ (
    .A(phase_adjust[4]),
    .B(_172_),
    .Y(_132_[4])
  );
  \$_OR_  _693_ (
    .A(phase_adjust[6]),
    .B(_173_),
    .Y(_132_[6])
  );
  \$_AND_  _694_ (
    .A(lock_counter[3]),
    .B(_128_[2]),
    .Y(_155_)
  );
  \$_AND_  _695_ (
    .A(lock_counter[5]),
    .B(_128_[4]),
    .Y(_156_)
  );
  \$_AND_  _696_ (
    .A(lock_counter[7]),
    .B(_128_[6]),
    .Y(_157_)
  );
  \$_AND_  _697_ (
    .A(_047_[3]),
    .B(_161_),
    .Y(_158_)
  );
  \$_AND_  _698_ (
    .A(_048_[1]),
    .B(_129_[3]),
    .Y(_159_)
  );
  \$_AND_  _699_ (
    .A(lock_counter[5]),
    .B(lock_counter[4]),
    .Y(_047_[2])
  );
  \$_OR_  _700_ (
    .A(_128_[3]),
    .B(_155_),
    .Y(_160_)
  );
  \$_OR_  _701_ (
    .A(_128_[5]),
    .B(_156_),
    .Y(_161_)
  );
  \$_OR_  _702_ (
    .A(_128_[7]),
    .B(_157_),
    .Y(_162_)
  );
  \$_OR_  _703_ (
    .A(_160_),
    .B(_047_[1]),
    .Y(_129_[3])
  );
  \$_OR_  _704_ (
    .A(_162_),
    .B(_158_),
    .Y(_163_)
  );
  \$_OR_  _705_ (
    .A(_163_),
    .B(_159_),
    .Y(_129_[7])
  );
  \$_AND_  _706_ (
    .A(lock_counter[1]),
    .B(lock_counter[0]),
    .Y(_119_[1])
  );
  \$_AND_  _707_ (
    .A(_047_[1]),
    .B(_119_[1]),
    .Y(_119_[3])
  );
  \$_AND_  _708_ (
    .A(_048_[1]),
    .B(_119_[3]),
    .Y(_119_[7])
  );
  \$_AND_  _709_ (
    .A(lock_counter[3]),
    .B(lock_counter[2]),
    .Y(_047_[1])
  );
  \$_AND_  _710_ (
    .A(lock_counter[7]),
    .B(lock_counter[6]),
    .Y(_047_[3])
  );
  \$_AND_  _711_ (
    .A(_047_[3]),
    .B(_047_[2]),
    .Y(_048_[1])
  );
  \$_AND_  _712_ (
    .A(_047_[2]),
    .B(_119_[3]),
    .Y(_119_[5])
  );
  \$_AND_  _713_ (
    .A(lock_counter[2]),
    .B(_119_[1]),
    .Y(_119_[2])
  );
  \$_AND_  _714_ (
    .A(lock_counter[4]),
    .B(_119_[3]),
    .Y(_119_[4])
  );
  \$_AND_  _715_ (
    .A(lock_counter[6]),
    .B(_119_[5]),
    .Y(_119_[6])
  );
  assign _047_[0] = _119_[1];
  assign _048_[0] = _119_[3];
  assign _103_[1:0] = { _009_, _117_[0] };
  assign { _113_[31:16], _113_[0] } = { 16'h0000, cal_counter[0] };
  assign _114_[31:1] = { 16'h0000, cal_counter[15:1] };
  assign { _115_[31:16], _115_[0] } = { 15'h0000, _113_[15], _114_[0] };
  assign { _116_[31:8], _116_[0] } = { 24'h000000, phase_adjust[0] };
  assign _117_[31:1] = { 24'h000000, phase_adjust[7:1] };
  assign { _118_[31:8], _118_[0] } = { 23'h000000, _116_[7], _117_[0] };
  assign { _119_[31:8], _119_[0] } = { 24'h000000, lock_counter[0] };
  assign _120_[31:1] = { 24'h000000, lock_counter[7:1] };
  assign { _121_[31:8], _121_[0] } = { 23'h000000, _119_[7], _120_[0] };
  assign _122_[0] = _117_[0];
  assign _128_[0] = _120_[0];
  assign _129_[2:0] = 3'h7;
  assign { _132_[30:7], _132_[0] } = { _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], _132_[31], phase_adjust[0] };
  assign { _133_[30:8], _133_[0] } = { _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _133_[31], _117_[0] };
  assign cal_current_phase = phase_adjust;
  assign cal_locked = phase_locked;
  assign \delay_chain_qca[0] [7:1] = 7'h00;
  assign \delay_chain_qca[10] [7:1] = 7'h00;
  assign \delay_chain_qca[11] [7:1] = 7'h00;
  assign \delay_chain_qca[12] [7:1] = 7'h00;
  assign \delay_chain_qca[13] [7:1] = 7'h00;
  assign \delay_chain_qca[14] [7:1] = 7'h00;
  assign \delay_chain_qca[15] [7:1] = 7'h00;
  assign \delay_chain_qca[16] [7:1] = 7'h00;
  assign \delay_chain_qca[17] [7:1] = 7'h00;
  assign \delay_chain_qca[18] [7:1] = 7'h00;
  assign \delay_chain_qca[19] [7:1] = 7'h00;
  assign \delay_chain_qca[1] [7:1] = 7'h00;
  assign \delay_chain_qca[20] [7:1] = 7'h00;
  assign \delay_chain_qca[21] [7:1] = 7'h00;
  assign \delay_chain_qca[22] [7:1] = 7'h00;
  assign \delay_chain_qca[23] [7:1] = 7'h00;
  assign \delay_chain_qca[24] [7:1] = 7'h00;
  assign \delay_chain_qca[25] [7:1] = 7'h00;
  assign \delay_chain_qca[26] [7:1] = 7'h00;
  assign \delay_chain_qca[27] [7:1] = 7'h00;
  assign \delay_chain_qca[28] [7:1] = 7'h00;
  assign \delay_chain_qca[29] [7:1] = 7'h00;
  assign \delay_chain_qca[2] [7:1] = 7'h00;
  assign \delay_chain_qca[30] [7:1] = 7'h00;
  assign \delay_chain_qca[31] [7:1] = 7'h00;
  assign \delay_chain_qca[32] [7:1] = 7'h00;
  assign \delay_chain_qca[33] [7:1] = 7'h00;
  assign \delay_chain_qca[34] [7:1] = 7'h00;
  assign \delay_chain_qca[35] [7:1] = 7'h00;
  assign \delay_chain_qca[36] [7:1] = 7'h00;
  assign \delay_chain_qca[37] [7:1] = 7'h00;
  assign \delay_chain_qca[38] [7:1] = 7'h00;
  assign \delay_chain_qca[39] [7:1] = 7'h00;
  assign \delay_chain_qca[3] [7:1] = 7'h00;
  assign \delay_chain_qca[40] [7:1] = 7'h00;
  assign \delay_chain_qca[41] [7:1] = 7'h00;
  assign \delay_chain_qca[42] [7:1] = 7'h00;
  assign \delay_chain_qca[43] [7:1] = 7'h00;
  assign \delay_chain_qca[44] [7:1] = 7'h00;
  assign \delay_chain_qca[45] [7:1] = 7'h00;
  assign \delay_chain_qca[46] [7:1] = 7'h00;
  assign \delay_chain_qca[47] [7:1] = 7'h00;
  assign \delay_chain_qca[48] [7:1] = 7'h00;
  assign \delay_chain_qca[49] [7:1] = 7'h00;
  assign \delay_chain_qca[4] [7:1] = 7'h00;
  assign \delay_chain_qca[50] [7:1] = 7'h00;
  assign \delay_chain_qca[51] [7:1] = 7'h00;
  assign \delay_chain_qca[52] [7:1] = 7'h00;
  assign \delay_chain_qca[53] [7:1] = 7'h00;
  assign \delay_chain_qca[54] [7:1] = 7'h00;
  assign \delay_chain_qca[55] [7:1] = 7'h00;
  assign \delay_chain_qca[5] [7:1] = 7'h00;
  assign \delay_chain_qca[6] [7:1] = 7'h00;
  assign \delay_chain_qca[7] [7:1] = 7'h00;
  assign \delay_chain_qca[8] [7:1] = 7'h00;
  assign \delay_chain_qca[9] [7:1] = 7'h00;
  assign \delay_chain_qck[0] [7:1] = 7'h00;
  assign \delay_chain_qck[1] [7:1] = 7'h00;
  assign \delay_chain_qck[2] [7:1] = 7'h00;
  assign \delay_chain_qck[3] [7:1] = 7'h00;
  assign \delay_chain_qck[4] [7:1] = 7'h00;
  assign \delay_chain_qck[5] [7:1] = 7'h00;
  assign \delay_chain_qck[6] [7:1] = 7'h00;
  assign \delay_chain_qck[7] [7:1] = 7'h00;
  assign gate_status = { 2'h0, phase_locked, calibration_active, cal_done, qca_gated, qck_gated, gate_enable };
endmodule
