/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/clock_gate.sv:13.1-237.23" *)
module clock_gate(clk_in, rst_n, enable, test_mode, clk_out);
  (* src = "rtl/clock_gate.sv:45.9-45.20" *)
  wire clk_gate_en;
  (* src = "rtl/clock_gate.sv:23.16-23.22" *)
  input clk_in;
  wire clk_in;
  (* src = "rtl/clock_gate.sv:35.16-35.23" *)
  output clk_out;
  wire clk_out;
  (* src = "rtl/clock_gate.sv:29.16-29.22" *)
  input enable;
  wire enable;
  (* src = "rtl/clock_gate.sv:43.9-43.23" *)
  reg enable_latched;
  (* src = "rtl/clock_gate.sv:42.9-42.20" *)
  wire enable_sync;
  (* src = "rtl/clock_gate.sv:55.13-55.27" *)
  reg \gen_safe_enable.enable_sync_q1 ;
  (* src = "rtl/clock_gate.sv:55.29-55.43" *)
  reg \gen_safe_enable.enable_sync_q2 ;
  (* src = "rtl/clock_gate.sv:24.16-24.21" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/clock_gate.sv:30.16-30.25" *)
  input test_mode;
  wire test_mode;
  (* src = "rtl/clock_gate.sv:46.9-46.25" *)
  wire test_mode_active;
  assign clk_gate_en = test_mode | \gen_safe_enable.enable_sync_q2 ;
  assign clk_out = clk_in & enable_latched;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/clock_gate.sv:68.9-76.12" *)
  always @(posedge clk_in)
    if (!rst_n) \gen_safe_enable.enable_sync_q2  <= 1'h0;
    else \gen_safe_enable.enable_sync_q2  <= \gen_safe_enable.enable_sync_q1 ;
  (* src = "rtl/clock_gate.sv:0.0-0.0" *)
  always @*
    if (!clk_in) enable_latched = clk_gate_en;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/clock_gate.sv:68.9-76.12" *)
  always @(posedge clk_in)
    if (!rst_n) \gen_safe_enable.enable_sync_q1  <= 1'h0;
    else \gen_safe_enable.enable_sync_q1  <= enable;
  assign enable_sync = \gen_safe_enable.enable_sync_q2 ;
  assign test_mode_active = test_mode;
endmodule
