/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/cmd_latency_ctrl.sv:23.1-180.10" *)
module cmd_latency_ctrl(clk, rst_n, mr13_data, mr13_valid, mr13_ready, cmd_in_data, cmd_in_valid, cmd_in_ready, cmd_out_data, cmd_out_valid, cmd_out_ready, current_latency, latency_enabled, latency_ctrl_busy);
  wire [3:0] _000_;
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  wire _001_;
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  wire _002_;
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  wire [3:0] _003_;
  wire _004_;
  (* src = "rtl/cmd_latency_ctrl.sv:109.18-109.42" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  (* src = "rtl/cmd_latency_ctrl.sv:30.35-30.38" *)
  input clk;
  wire clk;
  (* src = "rtl/cmd_latency_ctrl.sv:74.35-74.45" *)
  reg [7:0] cmd_buffer;
  (* src = "rtl/cmd_latency_ctrl.sv:75.35-75.51" *)
  reg cmd_buffer_valid;
  (* src = "rtl/cmd_latency_ctrl.sv:44.35-44.46" *)
  input [7:0] cmd_in_data;
  wire [7:0] cmd_in_data;
  (* src = "rtl/cmd_latency_ctrl.sv:46.35-46.47" *)
  output cmd_in_ready;
  wire cmd_in_ready;
  (* src = "rtl/cmd_latency_ctrl.sv:45.35-45.47" *)
  input cmd_in_valid;
  wire cmd_in_valid;
  (* src = "rtl/cmd_latency_ctrl.sv:50.35-50.47" *)
  output [7:0] cmd_out_data;
  wire [7:0] cmd_out_data;
  (* src = "rtl/cmd_latency_ctrl.sv:52.35-52.48" *)
  input cmd_out_ready;
  wire cmd_out_ready;
  (* src = "rtl/cmd_latency_ctrl.sv:51.35-51.48" *)
  output cmd_out_valid;
  wire cmd_out_valid;
  (* src = "rtl/cmd_latency_ctrl.sv:79.35-79.43" *)
  reg counting;
  (* src = "rtl/cmd_latency_ctrl.sv:56.36-56.51" *)
  output [3:0] current_latency;
  wire [3:0] current_latency;
  (* src = "rtl/cmd_latency_ctrl.sv:78.35-78.50" *)
  reg [3:0] latency_counter;
  (* src = "rtl/cmd_latency_ctrl.sv:58.35-58.52" *)
  output latency_ctrl_busy;
  wire latency_ctrl_busy;
  (* src = "rtl/cmd_latency_ctrl.sv:67.35-67.49" *)
  wire latency_enable;
  (* src = "rtl/cmd_latency_ctrl.sv:57.35-57.50" *)
  output latency_enabled;
  wire latency_enabled;
  (* src = "rtl/cmd_latency_ctrl.sv:66.35-66.47" *)
  wire [2:0] latency_mode;
  (* src = "rtl/cmd_latency_ctrl.sv:38.35-38.44" *)
  input [7:0] mr13_data;
  wire [7:0] mr13_data;
  (* src = "rtl/cmd_latency_ctrl.sv:40.35-40.45" *)
  output mr13_ready;
  wire mr13_ready;
  (* src = "rtl/cmd_latency_ctrl.sv:39.35-39.45" *)
  input mr13_valid;
  wire mr13_valid;
  (* src = "rtl/cmd_latency_ctrl.sv:31.35-31.40" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/cmd_latency_ctrl.sv:71.35-71.49" *)
  reg [3:0] stored_latency;
  assign _049_ = _044_ & _048_;
  assign _003_[2] = _042_ | _049_;
  assign _050_ = latency_counter[3] & _011_;
  assign _051_ = mr13_data[3] & stored_latency[3];
  assign _052_ = _001_ & _051_;
  assign _053_ = _050_ | _052_;
  assign _054_ = _022_ & _053_;
  assign _055_ = latency_counter[3] & _043_;
  assign _003_[3] = _054_ | _055_;
  assign _000_[3] = mr13_data[1] & mr13_data[2];
  assign _000_[2] = mr13_data[1] ^ mr13_data[2];
  assign _006_ = ~latency_counter[1];
  assign _007_ = ~latency_counter[0];
  assign _008_ = ~cmd_buffer_valid;
  assign mr13_ready = ~counting;
  assign _009_ = ~cmd_in_valid;
  assign _010_ = ~mr13_data[3];
  assign _000_[1] = ~mr13_data[1];
  assign _011_ = cmd_buffer_valid | _009_;
  assign _001_ = ~_011_;
  assign cmd_out_valid = cmd_buffer_valid & mr13_ready;
  assign _012_ = cmd_out_ready & cmd_out_valid;
  assign _004_ = _001_ | _012_;
  assign _005_ = mr13_ready & mr13_valid;
  assign _013_ = mr13_ready & cmd_out_ready;
  assign cmd_in_ready = _008_ | _013_;
  assign latency_ctrl_busy = cmd_buffer_valid | counting;
  assign _014_ = ~latency_ctrl_busy;
  assign _015_ = _006_ & _007_;
  assign _016_ = latency_counter[1] | latency_counter[0];
  assign _017_ = latency_counter[2] | _016_;
  assign _018_ = ~_017_;
  assign _019_ = latency_counter[3] | _017_;
  assign _020_ = ~_019_;
  assign _021_ = counting & _019_;
  assign _022_ = mr13_ready | _020_;
  assign _023_ = cmd_in_valid & _014_;
  assign _002_ = _021_ | _023_;
  assign _024_ = latency_counter[0] & counting;
  assign _025_ = ~_024_;
  assign _026_ = latency_counter[0] & _011_;
  assign _027_ = stored_latency[0] & mr13_data[3];
  assign _028_ = _001_ & _027_;
  assign _029_ = _026_ | _028_;
  assign _030_ = _021_ | _029_;
  assign _003_[0] = _025_ & _030_;
  assign _031_ = _011_ & _022_;
  assign _032_ = _024_ | _031_;
  assign _033_ = latency_counter[1] & _032_;
  assign _034_ = _010_ | stored_latency[1];
  assign _035_ = _001_ & _034_;
  assign _036_ = _022_ & _035_;
  assign _037_ = _015_ & _021_;
  assign _038_ = _036_ | _037_;
  assign _003_[1] = _033_ | _038_;
  assign _039_ = latency_counter[2] & _016_;
  assign _040_ = latency_counter[3] & _018_;
  assign _041_ = _039_ | _040_;
  assign _042_ = counting & _041_;
  assign _043_ = counting & _017_;
  assign _044_ = ~_043_;
  assign _045_ = latency_counter[2] & _011_;
  assign _046_ = mr13_data[3] & stored_latency[2];
  assign _047_ = _001_ & _046_;
  assign _048_ = _045_ | _047_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_latency[0] <= 1'h0;
    else if (_005_) stored_latency[0] <= mr13_data[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_latency[1] <= 1'h1;
    else if (_005_) stored_latency[1] <= _000_[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_latency[2] <= 1'h0;
    else if (_005_) stored_latency[2] <= _000_[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stored_latency[3] <= 1'h0;
    else if (_005_) stored_latency[3] <= _000_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer_valid <= 1'h0;
    else if (_004_) cmd_buffer_valid <= _001_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) latency_counter[0] <= 1'h0;
    else latency_counter[0] <= _003_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) latency_counter[1] <= 1'h0;
    else latency_counter[1] <= _003_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) latency_counter[2] <= 1'h0;
    else latency_counter[2] <= _003_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) latency_counter[3] <= 1'h0;
    else latency_counter[3] <= _003_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) counting <= 1'h0;
    else counting <= _002_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[0] <= 1'h0;
    else if (!_011_) cmd_buffer[0] <= cmd_in_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[1] <= 1'h0;
    else if (!_011_) cmd_buffer[1] <= cmd_in_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[2] <= 1'h0;
    else if (!_011_) cmd_buffer[2] <= cmd_in_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[3] <= 1'h0;
    else if (!_011_) cmd_buffer[3] <= cmd_in_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[4] <= 1'h0;
    else if (!_011_) cmd_buffer[4] <= cmd_in_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[5] <= 1'h0;
    else if (!_011_) cmd_buffer[5] <= cmd_in_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[6] <= 1'h0;
    else if (!_011_) cmd_buffer[6] <= cmd_in_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/cmd_latency_ctrl.sv:131.3-161.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cmd_buffer[7] <= 1'h0;
    else if (!_011_) cmd_buffer[7] <= cmd_in_data[7];
  assign _000_[0] = mr13_data[0];
  assign cmd_out_data = cmd_buffer;
  assign current_latency = stored_latency;
  assign latency_enable = mr13_data[3];
  assign latency_enabled = mr13_data[3];
  assign latency_mode = mr13_data[2:0];
endmodule
