/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/dcalcsr_calibrator.sv:7.1-87.10" *)
module dcalcsr_calibrator(clk, rst_n, calib_enable, dck_phase_cfg, csn_phase_cfg, dck_aligned, csn_aligned, dck_phase, csn_phase, dck_calib_out, csn_calib_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/dcalcsr_calibrator.sv:0.0-0.0|rtl/dcalcsr_calibrator.sv:47.9-71.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/dcalcsr_calibrator.sv:0.0-0.0|rtl/dcalcsr_calibrator.sv:47.9-71.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [11:0] _034_;
  (* src = "rtl/dcalcsr_calibrator.sv:34.11-34.20" *)
  reg [1:0] cal_state;
  (* src = "rtl/dcalcsr_calibrator.sv:35.12-35.21" *)
  reg [11:0] cal_timer;
  (* src = "rtl/dcalcsr_calibrator.sv:14.29-14.41" *)
  input calib_enable;
  wire calib_enable;
  (* src = "rtl/dcalcsr_calibrator.sv:12.29-12.32" *)
  input clk;
  wire clk;
  (* src = "rtl/dcalcsr_calibrator.sv:19.29-19.40" *)
  output csn_aligned;
  wire csn_aligned;
  (* src = "rtl/dcalcsr_calibrator.sv:25.29-25.42" *)
  output csn_calib_out;
  wire csn_calib_out;
  (* src = "rtl/dcalcsr_calibrator.sv:21.38-21.47" *)
  output [3:0] csn_phase;
  reg [3:0] csn_phase;
  (* src = "rtl/dcalcsr_calibrator.sv:16.39-16.52" *)
  input [3:0] csn_phase_cfg;
  wire [3:0] csn_phase_cfg;
  (* src = "rtl/dcalcsr_calibrator.sv:18.29-18.40" *)
  output dck_aligned;
  reg dck_aligned;
  (* src = "rtl/dcalcsr_calibrator.sv:24.29-24.42" *)
  output dck_calib_out;
  wire dck_calib_out;
  (* src = "rtl/dcalcsr_calibrator.sv:20.38-20.47" *)
  output [3:0] dck_phase;
  reg [3:0] dck_phase;
  (* src = "rtl/dcalcsr_calibrator.sv:15.39-15.52" *)
  input [3:0] dck_phase_cfg;
  wire [3:0] dck_phase_cfg;
  (* src = "rtl/dcalcsr_calibrator.sv:13.29-13.34" *)
  input rst_n;
  wire rst_n;
  assign _000_ = ~cal_state[1];
  assign _004_ = ~cal_state[0];
  assign _005_ = ~cal_timer[0];
  assign _006_ = _000_ & cal_state[0];
  assign _002_ = ~_006_;
  assign _003_ = _000_ | cal_state[0];
  assign _007_ = cal_timer[11] | cal_timer[10];
  assign _001_ = _002_ | _007_;
  assign dck_calib_out = dck_phase[3] & dck_aligned;
  assign csn_calib_out = dck_aligned & csn_phase[3];
  assign _034_[0] = _005_ & _006_;
  assign _008_ = cal_timer[1] & cal_timer[0];
  assign _009_ = cal_timer[1] ^ cal_timer[0];
  assign _034_[1] = _006_ & _009_;
  assign _010_ = cal_timer[2] & _008_;
  assign _011_ = cal_timer[2] ^ _008_;
  assign _034_[2] = _006_ & _011_;
  assign _012_ = cal_timer[3] & _010_;
  assign _013_ = cal_timer[3] ^ _010_;
  assign _034_[3] = _006_ & _013_;
  assign _014_ = cal_timer[4] & _012_;
  assign _015_ = cal_timer[4] ^ _012_;
  assign _034_[4] = _006_ & _015_;
  assign _016_ = cal_timer[5] & _014_;
  assign _017_ = ~_016_;
  assign _018_ = cal_timer[5] | _014_;
  assign _019_ = _006_ & _018_;
  assign _034_[5] = _017_ & _019_;
  assign _020_ = cal_timer[6] & _016_;
  assign _021_ = cal_timer[6] ^ _016_;
  assign _034_[6] = _006_ & _021_;
  assign _022_ = cal_timer[7] & _020_;
  assign _023_ = cal_timer[7] ^ _020_;
  assign _034_[7] = _006_ & _023_;
  assign _024_ = cal_timer[8] & _022_;
  assign _025_ = cal_timer[8] ^ _022_;
  assign _034_[8] = _006_ & _025_;
  assign _026_ = cal_timer[9] & _024_;
  assign _027_ = cal_timer[9] ^ _024_;
  assign _034_[9] = _006_ & _027_;
  assign _028_ = cal_timer[10] & _026_;
  assign _029_ = cal_timer[10] ^ _026_;
  assign _034_[10] = _006_ & _029_;
  assign _030_ = cal_timer[11] ^ _028_;
  assign _034_[11] = _006_ & _030_;
  assign _031_ = _004_ & calib_enable;
  assign _033_[0] = cal_state[1] | _031_;
  assign _032_ = _006_ & _007_;
  assign _033_[1] = cal_state[1] | _032_;
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_aligned <= 1'h0;
    else if (!_003_) dck_aligned <= 1'h1;
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_phase[0] <= 1'h0;
    else if (_006_) dck_phase[0] <= dck_phase_cfg[0];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_phase[1] <= 1'h0;
    else if (_006_) dck_phase[1] <= dck_phase_cfg[1];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_phase[2] <= 1'h0;
    else if (_006_) dck_phase[2] <= dck_phase_cfg[2];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_phase[3] <= 1'h0;
    else if (_006_) dck_phase[3] <= dck_phase_cfg[3];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) csn_phase[0] <= 1'h0;
    else if (_006_) csn_phase[0] <= csn_phase_cfg[0];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) csn_phase[1] <= 1'h0;
    else if (_006_) csn_phase[1] <= csn_phase_cfg[1];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) csn_phase[2] <= 1'h0;
    else if (_006_) csn_phase[2] <= csn_phase_cfg[2];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) csn_phase[3] <= 1'h0;
    else if (_006_) csn_phase[3] <= csn_phase_cfg[3];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_state[0] <= 1'h0;
    else if (_001_) cal_state[0] <= _033_[0];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_state[1] <= 1'h0;
    else if (_001_) cal_state[1] <= _033_[1];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[0] <= 1'h0;
    else if (!cal_state[1]) cal_timer[0] <= _034_[0];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[1] <= 1'h0;
    else if (!cal_state[1]) cal_timer[1] <= _034_[1];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[2] <= 1'h0;
    else if (!cal_state[1]) cal_timer[2] <= _034_[2];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[3] <= 1'h0;
    else if (!cal_state[1]) cal_timer[3] <= _034_[3];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[4] <= 1'h0;
    else if (!cal_state[1]) cal_timer[4] <= _034_[4];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[5] <= 1'h0;
    else if (!cal_state[1]) cal_timer[5] <= _034_[5];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[6] <= 1'h0;
    else if (!cal_state[1]) cal_timer[6] <= _034_[6];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[7] <= 1'h0;
    else if (!cal_state[1]) cal_timer[7] <= _034_[7];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[8] <= 1'h0;
    else if (!cal_state[1]) cal_timer[8] <= _034_[8];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[9] <= 1'h0;
    else if (!cal_state[1]) cal_timer[9] <= _034_[9];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[10] <= 1'h0;
    else if (!cal_state[1]) cal_timer[10] <= _034_[10];
  (* src = "rtl/dcalcsr_calibrator.sv:38.1-73.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cal_timer[11] <= 1'h0;
    else if (!cal_state[1]) cal_timer[11] <= _034_[11];
  assign csn_aligned = dck_aligned;
endmodule
