/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/dck_phase_calib.sv:5.1-95.10" *)
module dck_phase_calib(clk, rst_n, dck_in, calib_en, phase_cfg, monitor_req, phase_cur, calib_done, calib_err, dck_aligned, runtime_calib_req, runtime_calib_done, runtime_calib_err);
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* src = "rtl/dck_phase_calib.sv:15.28-15.38" *)
  output calib_done;
  wire calib_done;
  (* src = "rtl/dck_phase_calib.sv:11.28-11.36" *)
  input calib_en;
  wire calib_en;
  (* src = "rtl/dck_phase_calib.sv:16.28-16.37" *)
  output calib_err;
  wire calib_err;
  (* src = "rtl/dck_phase_calib.sv:27.9-27.21" *)
  reg calib_status;
  (* src = "rtl/dck_phase_calib.sv:8.28-8.31" *)
  input clk;
  wire clk;
  (* src = "rtl/dck_phase_calib.sv:17.28-17.39" *)
  output dck_aligned;
  wire dck_aligned;
  (* src = "rtl/dck_phase_calib.sv:10.28-10.34" *)
  input dck_in;
  wire dck_in;
  (* src = "rtl/dck_phase_calib.sv:27.37-27.43" *)
  reg dck_ok;
  (* src = "rtl/dck_phase_calib.sv:27.23-27.35" *)
  wire error_status;
  (* src = "rtl/dck_phase_calib.sv:13.28-13.39" *)
  input monitor_req;
  wire monitor_req;
  (* src = "rtl/dck_phase_calib.sv:12.35-12.44" *)
  input [7:0] phase_cfg;
  wire [7:0] phase_cfg;
  (* src = "rtl/dck_phase_calib.sv:14.35-14.44" *)
  output [7:0] phase_cur;
  wire [7:0] phase_cur;
  (* src = "rtl/dck_phase_calib.sv:25.27-25.36" *)
  reg [7:0] phase_reg;
  (* src = "rtl/dck_phase_calib.sv:9.28-9.33" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/dck_phase_calib.sv:20.28-20.46" *)
  output runtime_calib_done;
  wire runtime_calib_done;
  (* src = "rtl/dck_phase_calib.sv:21.28-21.45" *)
  output runtime_calib_err;
  wire runtime_calib_err;
  (* src = "rtl/dck_phase_calib.sv:19.28-19.45" *)
  input runtime_calib_req;
  wire runtime_calib_req;
  (* src = "rtl/dck_phase_calib.sv:28.9-28.21" *)
  reg runtime_done;
  (* src = "rtl/dck_phase_calib.sv:28.23-28.36" *)
  reg runtime_error;
  assign _03_ = phase_cfg[4] & phase_cfg[5];
  assign _04_ = phase_cfg[6] & phase_cfg[7];
  assign _05_ = _03_ & _04_;
  assign _06_ = phase_cfg[2] & phase_cfg[0];
  assign _07_ = phase_cfg[1] & phase_cfg[3];
  assign _08_ = _06_ & _07_;
  assign _09_ = _05_ & _08_;
  assign _10_ = ~_09_;
  assign _11_ = rst_n & runtime_calib_req;
  assign _01_ = _10_ & _11_;
  assign _12_ = phase_cfg[0] ^ phase_reg[0];
  assign _13_ = phase_cfg[5] ^ phase_reg[5];
  assign _14_ = _12_ | _13_;
  assign _15_ = phase_cfg[1] ^ phase_reg[1];
  assign _16_ = phase_cfg[7] ^ phase_reg[7];
  assign _17_ = _15_ | _16_;
  assign _18_ = _14_ | _17_;
  assign _19_ = phase_cfg[3] ^ phase_reg[3];
  assign _20_ = phase_cfg[6] ^ phase_reg[6];
  assign _21_ = _19_ | _20_;
  assign _22_ = phase_cfg[2] ^ phase_reg[2];
  assign _23_ = phase_cfg[4] ^ phase_reg[4];
  assign _24_ = _22_ | _23_;
  assign _25_ = _21_ | _24_;
  assign _26_ = _18_ | _25_;
  assign _02_ = calib_en & _26_;
  assign _00_ = runtime_calib_req & _09_;
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) dck_ok <= 1'h0;
    else if (calib_en) dck_ok <= 1'h1;
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[0] <= 1'h0;
    else if (_02_) phase_reg[0] <= phase_cfg[0];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[1] <= 1'h0;
    else if (_02_) phase_reg[1] <= phase_cfg[1];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[2] <= 1'h0;
    else if (_02_) phase_reg[2] <= phase_cfg[2];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[3] <= 1'h0;
    else if (_02_) phase_reg[3] <= phase_cfg[3];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[4] <= 1'h0;
    else if (_02_) phase_reg[4] <= phase_cfg[4];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[5] <= 1'h0;
    else if (_02_) phase_reg[5] <= phase_cfg[5];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[6] <= 1'h0;
    else if (_02_) phase_reg[6] <= phase_cfg[6];
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) phase_reg[7] <= 1'h0;
    else if (_02_) phase_reg[7] <= phase_cfg[7];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) runtime_done <= 1'h0;
    else runtime_done <= runtime_calib_req;
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) runtime_error <= 1'h0;
    else runtime_error <= _00_;
  (* src = "rtl/dck_phase_calib.sv:40.5-64.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) calib_status <= 1'h0;
    else calib_status <= calib_en;
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[0] <= phase_cfg[0];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[1] <= phase_cfg[1];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[2] <= phase_cfg[2];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[3] <= phase_cfg[3];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[4] <= phase_cfg[4];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[5] <= phase_cfg[5];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[6] <= phase_cfg[6];
  (* src = "rtl/dck_phase_calib.sv:67.5-85.8" *)
  always @(posedge clk)
    if (_01_) phase_reg[7] <= phase_cfg[7];
  assign calib_done = calib_status;
  assign calib_err = 1'h0;
  assign dck_aligned = dck_ok;
  assign error_status = 1'h0;
  assign phase_cur = phase_reg;
  assign runtime_calib_done = runtime_done;
  assign runtime_calib_err = runtime_error;
endmodule
