/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/dram_init_ctrl.sv:6.1-156.10" *)
module dram_init_ctrl(clk, rst_n, start, busy, done, cmd_valid, cmd_type, cmd_data, cmd_ready);
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  wire [2:0] _000_;
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  wire [13:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  (* src = "rtl/dram_init_ctrl.sv:19.18-19.22" *)
  output busy;
  wire busy;
  (* src = "rtl/dram_init_ctrl.sv:16.18-16.21" *)
  input clk;
  wire clk;
  (* src = "rtl/dram_init_ctrl.sv:24.25-24.33" *)
  output [31:0] cmd_data;
  wire [31:0] cmd_data;
  (* src = "rtl/dram_init_ctrl.sv:25.18-25.27" *)
  input cmd_ready;
  wire cmd_ready;
  (* src = "rtl/dram_init_ctrl.sv:23.24-23.32" *)
  output [4:0] cmd_type;
  wire [4:0] cmd_type;
  (* src = "rtl/dram_init_ctrl.sv:22.18-22.27" *)
  output cmd_valid;
  wire cmd_valid;
  (* src = "rtl/dram_init_ctrl.sv:20.18-20.22" *)
  output done;
  wire done;
  (* src = "rtl/dram_init_ctrl.sv:46.37-46.45" *)
  reg [2:0] mr_index;
  (* src = "rtl/dram_init_ctrl.sv:17.18-17.23" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/dram_init_ctrl.sv:18.18-18.23" *)
  input start;
  wire start;
  (* enum_value_0000 = "\\IDLE" *)
  (* enum_value_0001 = "\\POWERUP" *)
  (* enum_value_0010 = "\\NOP" *)
  (* enum_value_0011 = "\\PRECHARGE" *)
  (* enum_value_0100 = "\\ZQ_CAL" *)
  (* enum_value_0101 = "\\SET_MR" *)
  (* enum_value_0110 = "\\CKE_ENABLE" *)
  (* enum_value_0111 = "\\COMPLETE" *)
  (* src = "rtl/dram_init_ctrl.sv:40.9-40.14" *)
  (* wiretype = "\\state_t" *)
  wire [3:0] state;
  (* enum_value_0000 = "\\IDLE" *)
  (* enum_value_0001 = "\\POWERUP" *)
  (* enum_value_0010 = "\\NOP" *)
  (* enum_value_0011 = "\\PRECHARGE" *)
  (* enum_value_0100 = "\\ZQ_CAL" *)
  (* enum_value_0101 = "\\SET_MR" *)
  (* enum_value_0110 = "\\CKE_ENABLE" *)
  (* enum_value_0111 = "\\COMPLETE" *)
  (* src = "rtl/dram_init_ctrl.sv:40.16-40.25" *)
  (* wiretype = "\\state_t" *)
  wire [3:0] state_nxt;
  (* src = "rtl/dram_init_ctrl.sv:45.38-45.43" *)
  reg [13:0] timer;
  assign _066_ = ~state[1];
  assign _067_ = ~state[0];
  assign _069_ = ~timer[0];
  assign _070_ = ~mr_index[0];
  assign _071_ = _066_ & state[0];
  assign _068_ = ~state[2];
  assign _072_ = _071_ & state[2];
  assign _073_ = ~_072_;
  assign _074_ = state[1] | state[0];
  assign _075_ = ~_074_;
  assign _076_ = state[2] & _075_;
  assign _077_ = _068_ | _074_;
  assign _078_ = state[1] & state[0];
  assign _079_ = _068_ & _078_;
  assign _080_ = state[1] & _067_;
  assign cmd_type[2] = state[2] & _080_;
  assign _081_ = ~cmd_type[2];
  assign _082_ = _067_ & state[2];
  assign _083_ = _079_ | _082_;
  assign _084_ = _068_ & _080_;
  assign _085_ = _071_ & _068_;
  assign _086_ = ~_085_;
  assign _087_ = _084_ | _085_;
  assign _088_ = _083_ | _087_;
  assign busy = _072_ | _088_;
  assign _089_ = timer[6] | timer[5];
  assign _090_ = timer[7] | _089_;
  assign _091_ = timer[4] | _090_;
  assign _092_ = timer[8] & timer[9];
  assign _093_ = timer[10] & _092_;
  assign _094_ = _091_ & _093_;
  assign _095_ = timer[12] | timer[11];
  assign _096_ = _094_ | _095_;
  assign _097_ = timer[13] & _096_;
  assign _098_ = _086_ | _097_;
  assign _099_ = timer[8] | timer[12];
  assign _100_ = timer[10] | timer[11];
  assign _101_ = timer[13] | timer[9];
  assign _004_ = _100_ | _101_;
  assign _005_ = _099_ | _004_;
  assign _006_ = timer[7] | _005_;
  assign _007_ = _077_ | _006_;
  assign _008_ = _074_ | state[2];
  assign _009_ = ~_008_;
  assign _010_ = start | _008_;
  assign done = state[2] & _078_;
  assign _011_ = state[0] & state[2];
  assign _012_ = ~_011_;
  assign _013_ = _010_ & _012_;
  assign _014_ = _007_ & _013_;
  assign _015_ = _091_ | _005_;
  assign _016_ = _081_ | _015_;
  assign _017_ = timer[2] | timer[3];
  assign _018_ = timer[4] & _017_;
  assign _019_ = _090_ | _018_;
  assign _020_ = _005_ | _019_;
  assign _021_ = _066_ | state[2];
  assign _022_ = _020_ | _021_;
  assign _023_ = _016_ & _022_;
  assign _024_ = _014_ & _023_;
  assign _003_ = _098_ & _024_;
  assign _025_ = cmd_ready & _072_;
  assign _002_ = cmd_ready | _073_;
  assign cmd_valid = _072_ | _083_;
  assign _026_ = mr_index[0] & _072_;
  assign cmd_data[0] = cmd_type[2] | _026_;
  assign cmd_data[1] = mr_index[1] & _072_;
  assign cmd_data[2] = mr_index[2] & _072_;
  assign cmd_type[0] = _072_ | _079_;
  assign cmd_type[1] = _066_ & state[2];
  assign _001_[0] = _069_ & _088_;
  assign _027_ = timer[1] & timer[0];
  assign _028_ = timer[1] ^ timer[0];
  assign _001_[1] = _088_ & _028_;
  assign _029_ = timer[2] & _027_;
  assign _030_ = timer[2] ^ _027_;
  assign _001_[2] = _088_ & _030_;
  assign _031_ = timer[3] & _029_;
  assign _032_ = timer[3] ^ _029_;
  assign _001_[3] = _088_ & _032_;
  assign _033_ = timer[4] & _031_;
  assign _034_ = timer[4] ^ _031_;
  assign _001_[4] = _088_ & _034_;
  assign _035_ = timer[5] & _033_;
  assign _036_ = ~_035_;
  assign _037_ = timer[5] | _033_;
  assign _038_ = _088_ & _037_;
  assign _001_[5] = _036_ & _038_;
  assign _039_ = timer[6] & _035_;
  assign _040_ = timer[6] ^ _035_;
  assign _001_[6] = _088_ & _040_;
  assign _041_ = timer[7] & _039_;
  assign _042_ = timer[7] ^ _039_;
  assign _001_[7] = _088_ & _042_;
  assign _043_ = timer[8] & _041_;
  assign _044_ = timer[8] ^ _041_;
  assign _001_[8] = _088_ & _044_;
  assign _045_ = timer[9] ^ _043_;
  assign _001_[9] = _088_ & _045_;
  assign _046_ = _092_ & _041_;
  assign _047_ = timer[10] & _046_;
  assign _048_ = timer[10] ^ _046_;
  assign _001_[10] = _088_ & _048_;
  assign _049_ = timer[11] & _047_;
  assign _050_ = timer[11] ^ _047_;
  assign _001_[11] = _088_ & _050_;
  assign _051_ = timer[12] & _049_;
  assign _052_ = timer[12] ^ _049_;
  assign _001_[12] = _088_ & _052_;
  assign _053_ = timer[13] ^ _051_;
  assign _001_[13] = _088_ & _053_;
  assign _000_[0] = _070_ & _025_;
  assign _054_ = mr_index[0] & mr_index[1];
  assign _055_ = mr_index[0] ^ mr_index[1];
  assign _000_[1] = _025_ & _055_;
  assign _056_ = mr_index[2] ^ _054_;
  assign _000_[2] = _025_ & _056_;
  assign _057_ = cmd_type[2] & _015_;
  assign _058_ = _076_ & _006_;
  assign _059_ = _057_ | _058_;
  assign _060_ = start & _009_;
  assign _061_ = _084_ & _020_;
  assign _062_ = _060_ | _061_;
  assign state_nxt[0] = _059_ | _062_;
  assign _063_ = _085_ & _097_;
  assign _064_ = _057_ | _061_;
  assign state_nxt[1] = _063_ | _064_;
  assign _065_ = _079_ & _020_;
  assign state_nxt[2] = _059_ | _065_;
  reg \state_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[0]  <= 1'h0;
    else if (_003_) \state_reg[0]  <= state_nxt[0];
  assign state[0] = \state_reg[0] ;
  reg \state_reg[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[1]  <= 1'h0;
    else if (_003_) \state_reg[1]  <= state_nxt[1];
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[2]  <= 1'h0;
    else if (_003_) \state_reg[2]  <= state_nxt[2];
  assign state[2] = \state_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mr_index[0] <= 1'h0;
    else if (_002_) mr_index[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mr_index[1] <= 1'h0;
    else if (_002_) mr_index[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) mr_index[2] <= 1'h0;
    else if (_002_) mr_index[2] <= _000_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[0] <= 1'h0;
    else timer[0] <= _001_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[1] <= 1'h0;
    else timer[1] <= _001_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[2] <= 1'h0;
    else timer[2] <= _001_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[3] <= 1'h0;
    else timer[3] <= _001_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[4] <= 1'h0;
    else timer[4] <= _001_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[5] <= 1'h0;
    else timer[5] <= _001_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[6] <= 1'h0;
    else timer[6] <= _001_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[7] <= 1'h0;
    else timer[7] <= _001_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[8] <= 1'h0;
    else timer[8] <= _001_[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[9] <= 1'h0;
    else timer[9] <= _001_[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[10] <= 1'h0;
    else timer[10] <= _001_[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[11] <= 1'h0;
    else timer[11] <= _001_[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[12] <= 1'h0;
    else timer[12] <= _001_[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/dram_init_ctrl.sv:51.1-67.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer[13] <= 1'h0;
    else timer[13] <= _001_[13];
  assign cmd_data[31:3] = 29'h00000000;
  assign cmd_type[4:3] = 2'h0;
  assign state[3] = 1'h0;
  assign state_nxt[3] = 1'h0;
endmodule
