/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/error_log_reg.sv:24.1-232.10" *)
module error_log_reg(clk, rst_n, en, ecc_err_in, ecc_err_cnt_in, ecc_sbe_in, ecc_dbe_in, crc_err_in, crc_err_cnt_in, par_err_in, par_err_cnt_in, err_addr_in, err_position_in, reg_addr, reg_write, reg_write_data, reg_read_data, reg_read_valid, err_status_valid, any_error_detected, error_type_flags
, interrupt_out, total_error_cnt);
  (* src = "rtl/error_log_reg.sv:205.29-205.61" *)
  wire _000_;
  (* src = "rtl/error_log_reg.sv:205.29-205.61" *)
  wire _001_;
  (* src = "rtl/error_log_reg.sv:205.29-205.61" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  (* src = "rtl/error_log_reg.sv:58.31-58.49" *)
  output any_error_detected;
  wire any_error_detected;
  (* src = "rtl/error_log_reg.sv:30.31-30.34" *)
  input clk;
  wire clk;
  (* src = "rtl/error_log_reg.sv:41.31-41.45" *)
  input [15:0] crc_err_cnt_in;
  wire [15:0] crc_err_cnt_in;
  (* src = "rtl/error_log_reg.sv:40.31-40.41" *)
  input crc_err_in;
  wire crc_err_in;
  (* src = "rtl/error_log_reg.sv:38.31-38.41" *)
  input ecc_dbe_in;
  wire ecc_dbe_in;
  (* src = "rtl/error_log_reg.sv:36.31-36.45" *)
  input [15:0] ecc_err_cnt_in;
  wire [15:0] ecc_err_cnt_in;
  (* src = "rtl/error_log_reg.sv:35.31-35.41" *)
  input ecc_err_in;
  wire ecc_err_in;
  (* src = "rtl/error_log_reg.sv:37.31-37.41" *)
  input ecc_sbe_in;
  wire ecc_sbe_in;
  (* src = "rtl/error_log_reg.sv:32.31-32.33" *)
  input en;
  wire en;
  (* src = "rtl/error_log_reg.sv:46.31-46.42" *)
  input [31:0] err_addr_in;
  wire [31:0] err_addr_in;
  (* src = "rtl/error_log_reg.sv:47.31-47.46" *)
  input [7:0] err_position_in;
  wire [7:0] err_position_in;
  (* src = "rtl/error_log_reg.sv:57.31-57.47" *)
  output err_status_valid;
  wire err_status_valid;
  (* src = "rtl/error_log_reg.sv:59.31-59.47" *)
  output [7:0] error_type_flags;
  wire [7:0] error_type_flags;
  (* src = "rtl/error_log_reg.sv:60.31-60.44" *)
  output interrupt_out;
  wire interrupt_out;
  (* src = "rtl/error_log_reg.sv:44.31-44.45" *)
  input [15:0] par_err_cnt_in;
  wire [15:0] par_err_cnt_in;
  (* src = "rtl/error_log_reg.sv:43.31-43.41" *)
  input par_err_in;
  wire par_err_in;
  (* src = "rtl/error_log_reg.sv:50.33-50.41" *)
  input [4:0] reg_addr;
  wire [4:0] reg_addr;
  (* src = "rtl/error_log_reg.sv:83.16-83.33" *)
  wire [31:0] reg_crc_err_count;
  (* src = "rtl/error_log_reg.sv:86.16-86.29" *)
  wire [31:0] reg_dbe_count;
  (* src = "rtl/error_log_reg.sv:82.16-82.33" *)
  wire [31:0] reg_ecc_err_count;
  (* src = "rtl/error_log_reg.sv:88.16-88.28" *)
  reg [31:0] reg_err_ctrl;
  (* src = "rtl/error_log_reg.sv:81.16-81.30" *)
  wire [31:0] reg_err_status;
  (* src = "rtl/error_log_reg.sv:91.16-91.34" *)
  wire [7:0] reg_err_type_flags;
  (* src = "rtl/error_log_reg.sv:89.16-89.30" *)
  reg [31:0] reg_int_enable;
  (* src = "rtl/error_log_reg.sv:90.16-90.30" *)
  wire [31:0] reg_int_status;
  (* src = "rtl/error_log_reg.sv:87.16-87.33" *)
  reg [31:0] reg_last_err_addr;
  (* src = "rtl/error_log_reg.sv:84.16-84.33" *)
  wire [31:0] reg_par_err_count;
  (* src = "rtl/error_log_reg.sv:53.34-53.47" *)
  output [31:0] reg_read_data;
  wire [31:0] reg_read_data;
  (* src = "rtl/error_log_reg.sv:54.34-54.48" *)
  output reg_read_valid;
  wire reg_read_valid;
  (* src = "rtl/error_log_reg.sv:85.16-85.29" *)
  wire [31:0] reg_sbe_count;
  (* src = "rtl/error_log_reg.sv:51.33-51.42" *)
  input reg_write;
  wire reg_write;
  (* src = "rtl/error_log_reg.sv:52.34-52.48" *)
  input [31:0] reg_write_data;
  wire [31:0] reg_write_data;
  (* src = "rtl/error_log_reg.sv:31.31-31.36" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/error_log_reg.sv:61.31-61.46" *)
  output [15:0] total_error_cnt;
  wire [15:0] total_error_cnt;
  (* src = "rtl/error_log_reg.sv:222.16-222.28" *)
  wire [15:0] total_errors;
  assign _010_ = ~reg_addr[3];
  assign _011_ = ~reg_addr[2];
  assign _012_ = ~reg_addr[0];
  assign _013_ = ~reg_addr[4];
  assign reg_read_valid = ~reg_write;
  assign _014_ = ~reg_write_data[0];
  assign _015_ = ~reg_write_data[1];
  assign _016_ = ~reg_write_data[2];
  assign _017_ = ecc_err_in | crc_err_in;
  assign any_error_detected = par_err_in | _017_;
  assign _018_ = reg_int_status[0] | reg_int_status[1];
  assign interrupt_out = reg_int_status[2] | _018_;
  assign _019_ = reg_addr[1] | reg_addr[4];
  assign _020_ = ~_019_;
  assign _021_ = reg_addr[3] & _011_;
  assign _022_ = reg_addr[0] & _021_;
  assign _023_ = _020_ & _022_;
  assign _024_ = en & reg_write;
  assign _025_ = rst_n & _024_;
  assign _003_ = _023_ & _025_;
  assign _004_ = en & any_error_detected;
  assign _026_ = par_err_in & en;
  assign _005_ = reg_int_enable[2] & _026_;
  assign _027_ = crc_err_in & en;
  assign _006_ = reg_int_enable[1] & _027_;
  assign _028_ = ecc_err_in & en;
  assign _007_ = reg_int_enable[0] & _028_;
  assign _029_ = _012_ & _021_;
  assign _030_ = _020_ & _029_;
  assign _008_ = _024_ & _030_;
  assign _031_ = reg_addr[1] & _013_;
  assign _032_ = _010_ & reg_addr[2];
  assign _033_ = reg_addr[0] & _032_;
  assign _034_ = _031_ & _033_;
  assign _009_ = _024_ & _034_;
  assign _035_ = reg_int_enable[0] & _030_;
  assign _036_ = reg_err_ctrl[0] & _034_;
  assign _037_ = _035_ | _036_;
  assign _038_ = reg_int_status[0] & _023_;
  assign _039_ = _012_ & _032_;
  assign _040_ = _031_ & _039_;
  assign _041_ = reg_last_err_addr[0] & _040_;
  assign _042_ = _038_ | _041_;
  assign _043_ = _037_ | _042_;
  assign reg_read_data[0] = reg_read_valid & _043_;
  assign _044_ = reg_int_enable[1] & _030_;
  assign _045_ = reg_err_ctrl[1] & _034_;
  assign _046_ = _044_ | _045_;
  assign _047_ = reg_int_status[1] & _023_;
  assign _048_ = reg_last_err_addr[1] & _040_;
  assign _049_ = _047_ | _048_;
  assign _050_ = _046_ | _049_;
  assign reg_read_data[1] = reg_read_valid & _050_;
  assign _051_ = reg_int_enable[2] & _030_;
  assign _052_ = reg_err_ctrl[2] & _034_;
  assign _053_ = _051_ | _052_;
  assign _054_ = reg_int_status[2] & _023_;
  assign _055_ = reg_last_err_addr[2] & _040_;
  assign _056_ = _054_ | _055_;
  assign _057_ = _053_ | _056_;
  assign reg_read_data[2] = reg_read_valid & _057_;
  assign _058_ = reg_int_enable[3] & _030_;
  assign _059_ = reg_err_ctrl[3] & _034_;
  assign _060_ = reg_last_err_addr[3] & _040_;
  assign _061_ = _059_ | _060_;
  assign _062_ = _058_ | _061_;
  assign reg_read_data[3] = reg_read_valid & _062_;
  assign _063_ = reg_int_enable[4] & _030_;
  assign _064_ = reg_err_ctrl[4] & _034_;
  assign _065_ = reg_last_err_addr[4] & _040_;
  assign _066_ = _064_ | _065_;
  assign _067_ = _063_ | _066_;
  assign reg_read_data[4] = reg_read_valid & _067_;
  assign _068_ = reg_int_enable[5] & _030_;
  assign _069_ = reg_err_ctrl[5] & _034_;
  assign _070_ = reg_last_err_addr[5] & _040_;
  assign _071_ = _069_ | _070_;
  assign _072_ = _068_ | _071_;
  assign reg_read_data[5] = reg_read_valid & _072_;
  assign _073_ = reg_int_enable[6] & _030_;
  assign _074_ = reg_err_ctrl[6] & _034_;
  assign _075_ = reg_last_err_addr[6] & _040_;
  assign _076_ = _074_ | _075_;
  assign _077_ = _073_ | _076_;
  assign reg_read_data[6] = reg_read_valid & _077_;
  assign _078_ = reg_int_enable[7] & _030_;
  assign _079_ = reg_err_ctrl[7] & _034_;
  assign _080_ = reg_last_err_addr[7] & _040_;
  assign _081_ = _079_ | _080_;
  assign _082_ = _078_ | _081_;
  assign reg_read_data[7] = reg_read_valid & _082_;
  assign _083_ = reg_int_enable[8] & _030_;
  assign _084_ = reg_err_ctrl[8] & _034_;
  assign _085_ = reg_last_err_addr[8] & _040_;
  assign _086_ = _084_ | _085_;
  assign _087_ = _083_ | _086_;
  assign reg_read_data[8] = reg_read_valid & _087_;
  assign _088_ = reg_int_enable[9] & _030_;
  assign _089_ = reg_err_ctrl[9] & _034_;
  assign _090_ = reg_last_err_addr[9] & _040_;
  assign _091_ = _089_ | _090_;
  assign _092_ = _088_ | _091_;
  assign reg_read_data[9] = reg_read_valid & _092_;
  assign _093_ = reg_int_enable[10] & _030_;
  assign _094_ = reg_err_ctrl[10] & _034_;
  assign _095_ = reg_last_err_addr[10] & _040_;
  assign _096_ = _094_ | _095_;
  assign _097_ = _093_ | _096_;
  assign reg_read_data[10] = reg_read_valid & _097_;
  assign _098_ = reg_int_enable[11] & _030_;
  assign _099_ = reg_err_ctrl[11] & _034_;
  assign _100_ = reg_last_err_addr[11] & _040_;
  assign _101_ = _099_ | _100_;
  assign _102_ = _098_ | _101_;
  assign reg_read_data[11] = reg_read_valid & _102_;
  assign _103_ = reg_int_enable[12] & _030_;
  assign _104_ = reg_err_ctrl[12] & _034_;
  assign _105_ = reg_last_err_addr[12] & _040_;
  assign _106_ = _104_ | _105_;
  assign _107_ = _103_ | _106_;
  assign reg_read_data[12] = reg_read_valid & _107_;
  assign _108_ = reg_int_enable[13] & _030_;
  assign _109_ = reg_err_ctrl[13] & _034_;
  assign _110_ = reg_last_err_addr[13] & _040_;
  assign _111_ = _109_ | _110_;
  assign _112_ = _108_ | _111_;
  assign reg_read_data[13] = reg_read_valid & _112_;
  assign _113_ = reg_int_enable[14] & _030_;
  assign _114_ = reg_err_ctrl[14] & _034_;
  assign _115_ = reg_last_err_addr[14] & _040_;
  assign _116_ = _114_ | _115_;
  assign _117_ = _113_ | _116_;
  assign reg_read_data[14] = reg_read_valid & _117_;
  assign _118_ = reg_int_enable[15] & _030_;
  assign _119_ = reg_err_ctrl[15] & _034_;
  assign _120_ = reg_last_err_addr[15] & _040_;
  assign _121_ = _119_ | _120_;
  assign _122_ = _118_ | _121_;
  assign reg_read_data[15] = reg_read_valid & _122_;
  assign _123_ = reg_int_enable[16] & _030_;
  assign _124_ = reg_err_ctrl[16] & _034_;
  assign _125_ = reg_last_err_addr[16] & _040_;
  assign _126_ = _124_ | _125_;
  assign _127_ = _123_ | _126_;
  assign reg_read_data[16] = reg_read_valid & _127_;
  assign _128_ = reg_int_enable[17] & _030_;
  assign _129_ = reg_err_ctrl[17] & _034_;
  assign _130_ = reg_last_err_addr[17] & _040_;
  assign _131_ = _129_ | _130_;
  assign _132_ = _128_ | _131_;
  assign reg_read_data[17] = reg_read_valid & _132_;
  assign _133_ = reg_int_enable[18] & _030_;
  assign _134_ = reg_err_ctrl[18] & _034_;
  assign _135_ = reg_last_err_addr[18] & _040_;
  assign _136_ = _134_ | _135_;
  assign _137_ = _133_ | _136_;
  assign reg_read_data[18] = reg_read_valid & _137_;
  assign _138_ = reg_int_enable[19] & _030_;
  assign _139_ = reg_err_ctrl[19] & _034_;
  assign _140_ = reg_last_err_addr[19] & _040_;
  assign _141_ = _139_ | _140_;
  assign _142_ = _138_ | _141_;
  assign reg_read_data[19] = reg_read_valid & _142_;
  assign _143_ = reg_int_enable[20] & _030_;
  assign _144_ = reg_err_ctrl[20] & _034_;
  assign _145_ = reg_last_err_addr[20] & _040_;
  assign _146_ = _144_ | _145_;
  assign _147_ = _143_ | _146_;
  assign reg_read_data[20] = reg_read_valid & _147_;
  assign _148_ = reg_int_enable[21] & _030_;
  assign _149_ = reg_err_ctrl[21] & _034_;
  assign _150_ = reg_last_err_addr[21] & _040_;
  assign _151_ = _149_ | _150_;
  assign _152_ = _148_ | _151_;
  assign reg_read_data[21] = reg_read_valid & _152_;
  assign _153_ = reg_int_enable[22] & _030_;
  assign _154_ = reg_err_ctrl[22] & _034_;
  assign _155_ = reg_last_err_addr[22] & _040_;
  assign _156_ = _154_ | _155_;
  assign _157_ = _153_ | _156_;
  assign reg_read_data[22] = reg_read_valid & _157_;
  assign _158_ = reg_int_enable[23] & _030_;
  assign _159_ = reg_err_ctrl[23] & _034_;
  assign _160_ = reg_last_err_addr[23] & _040_;
  assign _161_ = _159_ | _160_;
  assign _162_ = _158_ | _161_;
  assign reg_read_data[23] = reg_read_valid & _162_;
  assign _163_ = reg_int_enable[24] & _030_;
  assign _164_ = reg_err_ctrl[24] & _034_;
  assign _165_ = reg_last_err_addr[24] & _040_;
  assign _166_ = _164_ | _165_;
  assign _167_ = _163_ | _166_;
  assign reg_read_data[24] = reg_read_valid & _167_;
  assign _168_ = reg_int_enable[25] & _030_;
  assign _169_ = reg_err_ctrl[25] & _034_;
  assign _170_ = reg_last_err_addr[25] & _040_;
  assign _171_ = _169_ | _170_;
  assign _172_ = _168_ | _171_;
  assign reg_read_data[25] = reg_read_valid & _172_;
  assign _173_ = reg_int_enable[26] & _030_;
  assign _174_ = reg_err_ctrl[26] & _034_;
  assign _175_ = reg_last_err_addr[26] & _040_;
  assign _176_ = _174_ | _175_;
  assign _177_ = _173_ | _176_;
  assign reg_read_data[26] = reg_read_valid & _177_;
  assign _178_ = reg_int_enable[27] & _030_;
  assign _179_ = reg_err_ctrl[27] & _034_;
  assign _180_ = reg_last_err_addr[27] & _040_;
  assign _181_ = _179_ | _180_;
  assign _182_ = _178_ | _181_;
  assign reg_read_data[27] = reg_read_valid & _182_;
  assign _183_ = reg_int_enable[28] & _030_;
  assign _184_ = reg_err_ctrl[28] & _034_;
  assign _185_ = reg_last_err_addr[28] & _040_;
  assign _186_ = _184_ | _185_;
  assign _187_ = _183_ | _186_;
  assign reg_read_data[28] = reg_read_valid & _187_;
  assign _188_ = reg_int_enable[29] & _030_;
  assign _189_ = reg_err_ctrl[29] & _034_;
  assign _190_ = reg_last_err_addr[29] & _040_;
  assign _191_ = _189_ | _190_;
  assign _192_ = _188_ | _191_;
  assign reg_read_data[29] = reg_read_valid & _192_;
  assign _193_ = reg_int_enable[30] & _030_;
  assign _194_ = reg_err_ctrl[30] & _034_;
  assign _195_ = reg_last_err_addr[30] & _040_;
  assign _196_ = _194_ | _195_;
  assign _197_ = _193_ | _196_;
  assign reg_read_data[30] = reg_read_valid & _197_;
  assign _198_ = reg_int_enable[31] & _030_;
  assign _199_ = reg_err_ctrl[31] & _034_;
  assign _200_ = reg_last_err_addr[31] & _040_;
  assign _201_ = _199_ | _200_;
  assign _202_ = _198_ | _201_;
  assign reg_read_data[31] = reg_read_valid & _202_;
  assign _000_ = reg_int_status[0] & _014_;
  assign _001_ = reg_int_status[1] & _015_;
  assign _002_ = reg_int_status[2] & _016_;
  reg \reg_int_status_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk)
    if (_003_) \reg_int_status_reg[0]  <= _000_;
  assign reg_int_status[0] = \reg_int_status_reg[0] ;
  reg \reg_int_status_reg[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk)
    if (_003_) \reg_int_status_reg[1]  <= _001_;
  assign reg_int_status[1] = \reg_int_status_reg[1] ;
  reg \reg_int_status_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk)
    if (_003_) \reg_int_status_reg[2]  <= _002_;
  assign reg_int_status[2] = \reg_int_status_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[0] <= 1'h0;
    else if (_009_) reg_err_ctrl[0] <= reg_write_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[1] <= 1'h0;
    else if (_009_) reg_err_ctrl[1] <= reg_write_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[2] <= 1'h0;
    else if (_009_) reg_err_ctrl[2] <= reg_write_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[3] <= 1'h0;
    else if (_009_) reg_err_ctrl[3] <= reg_write_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[4] <= 1'h0;
    else if (_009_) reg_err_ctrl[4] <= reg_write_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[5] <= 1'h0;
    else if (_009_) reg_err_ctrl[5] <= reg_write_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[6] <= 1'h0;
    else if (_009_) reg_err_ctrl[6] <= reg_write_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[7] <= 1'h0;
    else if (_009_) reg_err_ctrl[7] <= reg_write_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[8] <= 1'h0;
    else if (_009_) reg_err_ctrl[8] <= reg_write_data[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[9] <= 1'h0;
    else if (_009_) reg_err_ctrl[9] <= reg_write_data[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[10] <= 1'h0;
    else if (_009_) reg_err_ctrl[10] <= reg_write_data[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[11] <= 1'h0;
    else if (_009_) reg_err_ctrl[11] <= reg_write_data[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[12] <= 1'h0;
    else if (_009_) reg_err_ctrl[12] <= reg_write_data[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[13] <= 1'h0;
    else if (_009_) reg_err_ctrl[13] <= reg_write_data[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[14] <= 1'h0;
    else if (_009_) reg_err_ctrl[14] <= reg_write_data[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[15] <= 1'h0;
    else if (_009_) reg_err_ctrl[15] <= reg_write_data[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[16] <= 1'h0;
    else if (_009_) reg_err_ctrl[16] <= reg_write_data[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[17] <= 1'h0;
    else if (_009_) reg_err_ctrl[17] <= reg_write_data[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[18] <= 1'h0;
    else if (_009_) reg_err_ctrl[18] <= reg_write_data[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[19] <= 1'h0;
    else if (_009_) reg_err_ctrl[19] <= reg_write_data[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[20] <= 1'h0;
    else if (_009_) reg_err_ctrl[20] <= reg_write_data[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[21] <= 1'h0;
    else if (_009_) reg_err_ctrl[21] <= reg_write_data[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[22] <= 1'h0;
    else if (_009_) reg_err_ctrl[22] <= reg_write_data[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[23] <= 1'h0;
    else if (_009_) reg_err_ctrl[23] <= reg_write_data[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[24] <= 1'h0;
    else if (_009_) reg_err_ctrl[24] <= reg_write_data[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[25] <= 1'h0;
    else if (_009_) reg_err_ctrl[25] <= reg_write_data[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[26] <= 1'h0;
    else if (_009_) reg_err_ctrl[26] <= reg_write_data[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[27] <= 1'h0;
    else if (_009_) reg_err_ctrl[27] <= reg_write_data[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[28] <= 1'h0;
    else if (_009_) reg_err_ctrl[28] <= reg_write_data[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[29] <= 1'h0;
    else if (_009_) reg_err_ctrl[29] <= reg_write_data[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[30] <= 1'h0;
    else if (_009_) reg_err_ctrl[30] <= reg_write_data[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_err_ctrl[31] <= 1'h0;
    else if (_009_) reg_err_ctrl[31] <= reg_write_data[31];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[0] <= 1'h0;
    else if (_004_) reg_last_err_addr[0] <= err_addr_in[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[1] <= 1'h0;
    else if (_004_) reg_last_err_addr[1] <= err_addr_in[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[2] <= 1'h0;
    else if (_004_) reg_last_err_addr[2] <= err_addr_in[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[3] <= 1'h0;
    else if (_004_) reg_last_err_addr[3] <= err_addr_in[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[4] <= 1'h0;
    else if (_004_) reg_last_err_addr[4] <= err_addr_in[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[5] <= 1'h0;
    else if (_004_) reg_last_err_addr[5] <= err_addr_in[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[6] <= 1'h0;
    else if (_004_) reg_last_err_addr[6] <= err_addr_in[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[7] <= 1'h0;
    else if (_004_) reg_last_err_addr[7] <= err_addr_in[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[8] <= 1'h0;
    else if (_004_) reg_last_err_addr[8] <= err_addr_in[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[9] <= 1'h0;
    else if (_004_) reg_last_err_addr[9] <= err_addr_in[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[10] <= 1'h0;
    else if (_004_) reg_last_err_addr[10] <= err_addr_in[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[11] <= 1'h0;
    else if (_004_) reg_last_err_addr[11] <= err_addr_in[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[12] <= 1'h0;
    else if (_004_) reg_last_err_addr[12] <= err_addr_in[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[13] <= 1'h0;
    else if (_004_) reg_last_err_addr[13] <= err_addr_in[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[14] <= 1'h0;
    else if (_004_) reg_last_err_addr[14] <= err_addr_in[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[15] <= 1'h0;
    else if (_004_) reg_last_err_addr[15] <= err_addr_in[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[16] <= 1'h0;
    else if (_004_) reg_last_err_addr[16] <= err_addr_in[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[17] <= 1'h0;
    else if (_004_) reg_last_err_addr[17] <= err_addr_in[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[18] <= 1'h0;
    else if (_004_) reg_last_err_addr[18] <= err_addr_in[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[19] <= 1'h0;
    else if (_004_) reg_last_err_addr[19] <= err_addr_in[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[20] <= 1'h0;
    else if (_004_) reg_last_err_addr[20] <= err_addr_in[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[21] <= 1'h0;
    else if (_004_) reg_last_err_addr[21] <= err_addr_in[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[22] <= 1'h0;
    else if (_004_) reg_last_err_addr[22] <= err_addr_in[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[23] <= 1'h0;
    else if (_004_) reg_last_err_addr[23] <= err_addr_in[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[24] <= 1'h0;
    else if (_004_) reg_last_err_addr[24] <= err_addr_in[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[25] <= 1'h0;
    else if (_004_) reg_last_err_addr[25] <= err_addr_in[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[26] <= 1'h0;
    else if (_004_) reg_last_err_addr[26] <= err_addr_in[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[27] <= 1'h0;
    else if (_004_) reg_last_err_addr[27] <= err_addr_in[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[28] <= 1'h0;
    else if (_004_) reg_last_err_addr[28] <= err_addr_in[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[29] <= 1'h0;
    else if (_004_) reg_last_err_addr[29] <= err_addr_in[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[30] <= 1'h0;
    else if (_004_) reg_last_err_addr[30] <= err_addr_in[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_last_err_addr[31] <= 1'h0;
    else if (_004_) reg_last_err_addr[31] <= err_addr_in[31];
  reg \reg_int_status_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \reg_int_status_reg[2]  <= 1'h0;
    else if (_005_) \reg_int_status_reg[2]  <= 1'h1;
  assign reg_int_status[2] = \reg_int_status_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[0] <= 1'h0;
    else if (_008_) reg_int_enable[0] <= reg_write_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[1] <= 1'h0;
    else if (_008_) reg_int_enable[1] <= reg_write_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[2] <= 1'h0;
    else if (_008_) reg_int_enable[2] <= reg_write_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[3] <= 1'h0;
    else if (_008_) reg_int_enable[3] <= reg_write_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[4] <= 1'h0;
    else if (_008_) reg_int_enable[4] <= reg_write_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[5] <= 1'h0;
    else if (_008_) reg_int_enable[5] <= reg_write_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[6] <= 1'h0;
    else if (_008_) reg_int_enable[6] <= reg_write_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[7] <= 1'h0;
    else if (_008_) reg_int_enable[7] <= reg_write_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[8] <= 1'h0;
    else if (_008_) reg_int_enable[8] <= reg_write_data[8];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[9] <= 1'h0;
    else if (_008_) reg_int_enable[9] <= reg_write_data[9];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[10] <= 1'h0;
    else if (_008_) reg_int_enable[10] <= reg_write_data[10];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[11] <= 1'h0;
    else if (_008_) reg_int_enable[11] <= reg_write_data[11];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[12] <= 1'h0;
    else if (_008_) reg_int_enable[12] <= reg_write_data[12];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[13] <= 1'h0;
    else if (_008_) reg_int_enable[13] <= reg_write_data[13];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[14] <= 1'h0;
    else if (_008_) reg_int_enable[14] <= reg_write_data[14];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[15] <= 1'h0;
    else if (_008_) reg_int_enable[15] <= reg_write_data[15];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[16] <= 1'h0;
    else if (_008_) reg_int_enable[16] <= reg_write_data[16];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[17] <= 1'h0;
    else if (_008_) reg_int_enable[17] <= reg_write_data[17];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[18] <= 1'h0;
    else if (_008_) reg_int_enable[18] <= reg_write_data[18];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[19] <= 1'h0;
    else if (_008_) reg_int_enable[19] <= reg_write_data[19];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[20] <= 1'h0;
    else if (_008_) reg_int_enable[20] <= reg_write_data[20];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[21] <= 1'h0;
    else if (_008_) reg_int_enable[21] <= reg_write_data[21];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[22] <= 1'h0;
    else if (_008_) reg_int_enable[22] <= reg_write_data[22];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[23] <= 1'h0;
    else if (_008_) reg_int_enable[23] <= reg_write_data[23];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[24] <= 1'h0;
    else if (_008_) reg_int_enable[24] <= reg_write_data[24];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[25] <= 1'h0;
    else if (_008_) reg_int_enable[25] <= reg_write_data[25];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[26] <= 1'h0;
    else if (_008_) reg_int_enable[26] <= reg_write_data[26];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[27] <= 1'h0;
    else if (_008_) reg_int_enable[27] <= reg_write_data[27];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[28] <= 1'h0;
    else if (_008_) reg_int_enable[28] <= reg_write_data[28];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[29] <= 1'h0;
    else if (_008_) reg_int_enable[29] <= reg_write_data[29];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[30] <= 1'h0;
    else if (_008_) reg_int_enable[30] <= reg_write_data[30];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:181.3-212.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_int_enable[31] <= 1'h0;
    else if (_008_) reg_int_enable[31] <= reg_write_data[31];
  reg \reg_int_status_reg[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \reg_int_status_reg[1]  <= 1'h0;
    else if (_006_) \reg_int_status_reg[1]  <= 1'h1;
  assign reg_int_status[1] = \reg_int_status_reg[1] ;
  reg \reg_int_status_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/error_log_reg.sv:111.3-151.6" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \reg_int_status_reg[0]  <= 1'h0;
    else if (_007_) \reg_int_status_reg[0]  <= 1'h1;
  assign reg_int_status[0] = \reg_int_status_reg[0] ;
  assign err_status_valid = 1'h0;
  assign error_type_flags = { 3'h0, ecc_dbe_in, ecc_sbe_in, par_err_in, crc_err_in, ecc_err_in };
  assign reg_crc_err_count = 32'd0;
  assign reg_dbe_count = 32'd0;
  assign reg_ecc_err_count = 32'd0;
  assign reg_err_status = 32'd0;
  assign reg_err_type_flags = { 3'h0, ecc_dbe_in, ecc_sbe_in, par_err_in, crc_err_in, ecc_err_in };
  assign reg_int_status[31:3] = 29'h00000000;
  assign reg_par_err_count = 32'd0;
  assign reg_sbe_count = 32'd0;
  assign total_error_cnt = 16'h0000;
  assign total_errors = 16'h0000;
endmodule
