/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/i3c_hotjoin_addr_clkstr.sv:15.1-176.10" *)
module i3c_hotjoin_addr_clkstr(clk, rst_n, scl, sda, sda_oe, scl_oe, hj_event_req, hj_notify_host, da_assign_req, new_da, curr_da, da_assigned, cmd_rstdaa, cmd_enec, cmd_disec, cmd_setdasa, proto_err, clock_stretching);
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:19.28-19.31" *)
  input clk;
  wire clk;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:46.28-46.44" *)
  output clock_stretching;
  reg clock_stretching;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:41.28-41.37" *)
  output cmd_disec;
  wire cmd_disec;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:40.28-40.36" *)
  output cmd_enec;
  wire cmd_enec;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:39.28-39.38" *)
  output cmd_rstdaa;
  wire cmd_rstdaa;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:42.28-42.39" *)
  output cmd_setdasa;
  wire cmd_setdasa;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:35.35-35.42" *)
  output [6:0] curr_da;
  wire [6:0] curr_da;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:33.28-33.41" *)
  input da_assign_req;
  wire da_assign_req;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:36.28-36.39" *)
  output da_assigned;
  wire da_assigned;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:59.24-59.33" *)
  wire [6:0] da_shadow;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:29.28-29.40" *)
  input hj_event_req;
  wire hj_event_req;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:30.28-30.42" *)
  output hj_notify_host;
  wire hj_notify_host;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:34.35-34.41" *)
  input [6:0] new_da;
  wire [6:0] new_da;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:45.28-45.37" *)
  input proto_err;
  wire proto_err;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:20.28-20.33" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:23.28-23.31" *)
  input scl;
  wire scl;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:26.28-26.34" *)
  output scl_oe;
  wire scl_oe;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:24.28-24.31" *)
  input sda;
  wire sda;
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:25.28-25.34" *)
  output sda_oe;
  wire sda_oe;
  (* enum_value_000 = "\\IDLE" *)
  (* enum_value_001 = "\\HJ_WAIT" *)
  (* enum_value_010 = "\\HJ_NOTIFY" *)
  (* enum_value_011 = "\\DA_WAIT_REQ" *)
  (* enum_value_100 = "\\DA_ASSIGN" *)
  (* enum_value_101 = "\\DA_DONE" *)
  (* enum_value_110 = "\\STRETCH" *)
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:57.9-57.14" *)
  (* wiretype = "\\state_t" *)
  wire [2:0] state;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/i3c_hotjoin_addr_clkstr.sv:149.1-169.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) clock_stretching <= 1'h0;
    else clock_stretching <= proto_err;
  assign cmd_disec = 1'h0;
  assign cmd_enec = 1'h0;
  assign cmd_rstdaa = 1'h0;
  assign cmd_setdasa = 1'h0;
  assign curr_da = 7'h00;
  assign da_assigned = 1'h1;
  assign da_shadow = 7'h00;
  assign hj_notify_host = 1'h0;
  assign scl_oe = clock_stretching;
  assign state = 3'h6;
endmodule
