/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/pll_init_lock.sv:15.1-146.10" *)
module pll_init_lock(clk, rst_n, pll_config, pll_config_valid, pll_locked, pll_lock_pulse, pll_fault, state_dbg, ddr_clk_hook);
  (* src = "rtl/pll_init_lock.sv:45.5-73.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "rtl/pll_init_lock.sv:19.32-19.35" *)
  input clk;
  wire clk;
  (* src = "rtl/pll_init_lock.sv:27.32-27.44" *)
  output ddr_clk_hook;
  wire ddr_clk_hook;
  (* src = "rtl/pll_init_lock.sv:42.26-42.40" *)
  reg internal_fault;
  (* src = "rtl/pll_init_lock.sv:42.9-42.24" *)
  wire internal_locked;
  (* src = "rtl/pll_init_lock.sv:21.36-21.46" *)
  input [15:0] pll_config;
  wire [15:0] pll_config;
  (* src = "rtl/pll_init_lock.sv:22.32-22.48" *)
  input pll_config_valid;
  wire pll_config_valid;
  (* src = "rtl/pll_init_lock.sv:25.32-25.41" *)
  output pll_fault;
  reg pll_fault;
  (* src = "rtl/pll_init_lock.sv:24.32-24.46" *)
  output pll_lock_pulse;
  wire pll_lock_pulse;
  (* src = "rtl/pll_init_lock.sv:23.32-23.42" *)
  output pll_locked;
  wire pll_locked;
  (* src = "rtl/pll_init_lock.sv:40.16-40.27" *)
  wire [15:0] powerup_cnt;
  (* src = "rtl/pll_init_lock.sv:20.32-20.37" *)
  input rst_n;
  wire rst_n;
  (* enum_value_0000 = "\\S_IDLE" *)
  (* enum_value_0001 = "\\S_PWRUP" *)
  (* enum_value_0010 = "\\S_CFG" *)
  (* enum_value_0011 = "\\S_WAIT_LOCK" *)
  (* enum_value_0100 = "\\S_LOCKED" *)
  (* enum_value_0101 = "\\S_FAULT" *)
  (* src = "rtl/pll_init_lock.sv:39.17-39.22" *)
  (* wiretype = "\\pll_state_t" *)
  wire [3:0] state;
  (* src = "rtl/pll_init_lock.sv:26.34-26.43" *)
  output [3:0] state_dbg;
  wire [3:0] state_dbg;
  (* enum_value_0000 = "\\S_IDLE" *)
  (* enum_value_0001 = "\\S_PWRUP" *)
  (* enum_value_0010 = "\\S_CFG" *)
  (* enum_value_0011 = "\\S_WAIT_LOCK" *)
  (* enum_value_0100 = "\\S_LOCKED" *)
  (* enum_value_0101 = "\\S_FAULT" *)
  (* src = "rtl/pll_init_lock.sv:39.24-39.34" *)
  (* wiretype = "\\pll_state_t" *)
  wire [3:0] state_next;
  assign _02_ = ~state[2];
  assign _03_ = ~state[1];
  assign _04_ = _03_ | pll_config_valid;
  assign _05_ = state[1] | rst_n;
  assign _06_ = _02_ & _04_;
  assign _07_ = _05_ & _06_;
  assign _08_ = state[2] & _03_;
  assign _09_ = state[0] | _08_;
  assign state_next[0] = _07_ | _09_;
  assign _10_ = state[0] & _02_;
  assign _11_ = state[1] & _10_;
  assign _12_ = internal_fault & _11_;
  assign _00_ = _08_ | _12_;
  assign state_next[2] = state[2] | _12_;
  assign _13_ = internal_fault & _10_;
  assign _14_ = ~_13_;
  assign state_next[1] = state[1] & _14_;
  assign _15_ = pll_config[4] | pll_config[5];
  assign _16_ = pll_config[6] | pll_config[7];
  assign _17_ = _15_ | _16_;
  assign _18_ = pll_config[0] | pll_config[1];
  assign _19_ = pll_config[2] | pll_config[3];
  assign _20_ = _18_ | _19_;
  assign _21_ = _17_ | _20_;
  assign _22_ = pll_config[12] | pll_config[13];
  assign _23_ = pll_config[14] | pll_config[15];
  assign _24_ = _22_ | _23_;
  assign _25_ = pll_config[8] | pll_config[9];
  assign _26_ = pll_config[10] | pll_config[11];
  assign _27_ = _25_ | _26_;
  assign _28_ = _24_ | _27_;
  assign _29_ = _21_ | _28_;
  assign _30_ = ~_29_;
  assign _01_ = _11_ & _30_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pll_init_lock.sv:116.5-145.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) internal_fault <= 1'h0;
    else if (_01_) internal_fault <= 1'h1;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pll_init_lock.sv:45.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pll_fault <= 1'h0;
    else pll_fault <= _00_;
  reg \state_reg[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pll_init_lock.sv:45.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[0]  <= 1'h0;
    else \state_reg[0]  <= state_next[0];
  assign state[0] = \state_reg[0] ;
  reg \state_reg[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pll_init_lock.sv:45.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[1]  <= 1'h0;
    else \state_reg[1]  <= state_next[1];
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/pll_init_lock.sv:45.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \state_reg[2]  <= 1'h0;
    else \state_reg[2]  <= state_next[2];
  assign state[2] = \state_reg[2] ;
  assign ddr_clk_hook = 1'h0;
  assign internal_locked = 1'h0;
  assign pll_lock_pulse = 1'h0;
  assign pll_locked = 1'h0;
  assign powerup_cnt = 16'h0000;
  assign state[3] = 1'h0;
  assign state_dbg = { 1'h0, state[2:0] };
  assign state_next[3] = 1'h0;
endmodule
