/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/qck_controller.sv:27.1-107.10" *)
module qck_controller(clk, reset_n, ck_en, ca_ctrl, qca_ctrl, qck_mask, skip_req, prog_delay, ck_out, error);
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  wire [7:0] _000_;
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  (* src = "rtl/qck_controller.sv:35.41-35.48" *)
  input ca_ctrl;
  wire ca_ctrl;
  (* src = "rtl/qck_controller.sv:34.41-34.46" *)
  input [7:0] ck_en;
  wire [7:0] ck_en;
  (* src = "rtl/qck_controller.sv:40.41-40.47" *)
  output [7:0] ck_out;
  reg [7:0] ck_out;
  (* src = "rtl/qck_controller.sv:32.41-32.44" *)
  input clk;
  wire clk;
  (* src = "rtl/qck_controller.sv:45.33-45.40" *)
  reg [7:0] \en_pipe[0] ;
  (* src = "rtl/qck_controller.sv:45.33-45.40" *)
  reg [7:0] \en_pipe[1] ;
  (* src = "rtl/qck_controller.sv:41.41-41.46" *)
  output [7:0] error;
  reg [7:0] error;
  (* src = "rtl/qck_controller.sv:53.13-53.14" *)
  wire [31:0] i;
  (* src = "rtl/qck_controller.sv:46.33-46.42" *)
  reg [7:0] \mask_pipe[0] ;
  (* src = "rtl/qck_controller.sv:46.33-46.42" *)
  reg [7:0] \mask_pipe[1] ;
  (* src = "rtl/qck_controller.sv:39.45-39.55" *)
  input [31:0] prog_delay;
  wire [31:0] prog_delay;
  (* src = "rtl/qck_controller.sv:36.41-36.49" *)
  input qca_ctrl;
  wire qca_ctrl;
  (* src = "rtl/qck_controller.sv:37.41-37.49" *)
  input [7:0] qck_mask;
  wire [7:0] qck_mask;
  (* src = "rtl/qck_controller.sv:33.41-33.48" *)
  input reset_n;
  wire reset_n;
  (* src = "rtl/qck_controller.sv:47.33-47.42" *)
  reg [7:0] \skip_pipe[0] ;
  (* src = "rtl/qck_controller.sv:47.33-47.42" *)
  reg [7:0] \skip_pipe[1] ;
  (* src = "rtl/qck_controller.sv:38.41-38.49" *)
  input [7:0] skip_req;
  wire [7:0] skip_req;
  assign _002_ = ~\skip_pipe[1] [7];
  assign _003_ = ~\skip_pipe[1] [6];
  assign _004_ = ~\skip_pipe[1] [5];
  assign _005_ = ~\skip_pipe[1] [4];
  assign _006_ = ~\skip_pipe[1] [3];
  assign _007_ = ~\skip_pipe[1] [2];
  assign _008_ = ~\skip_pipe[1] [1];
  assign _009_ = ~\skip_pipe[1] [0];
  assign _010_ = ~\mask_pipe[1] [0];
  assign _011_ = ~\mask_pipe[1] [1];
  assign _012_ = ~\mask_pipe[1] [2];
  assign _013_ = ~\mask_pipe[1] [3];
  assign _014_ = ~\mask_pipe[1] [4];
  assign _015_ = ~\mask_pipe[1] [5];
  assign _016_ = ~\mask_pipe[1] [6];
  assign _017_ = ~\mask_pipe[1] [7];
  assign _018_ = _017_ & \en_pipe[1] [7];
  assign _000_[7] = \skip_pipe[1] [7] | _018_;
  assign _019_ = _016_ & \en_pipe[1] [6];
  assign _000_[6] = \skip_pipe[1] [6] | _019_;
  assign _020_ = _015_ & \en_pipe[1] [5];
  assign _000_[5] = \skip_pipe[1] [5] | _020_;
  assign _021_ = _014_ & \en_pipe[1] [4];
  assign _000_[4] = \skip_pipe[1] [4] | _021_;
  assign _022_ = _013_ & \en_pipe[1] [3];
  assign _000_[3] = \skip_pipe[1] [3] | _022_;
  assign _023_ = _012_ & \en_pipe[1] [2];
  assign _000_[2] = \skip_pipe[1] [2] | _023_;
  assign _024_ = _011_ & \en_pipe[1] [1];
  assign _000_[1] = \skip_pipe[1] [1] | _024_;
  assign _025_ = _010_ & \en_pipe[1] [0];
  assign _000_[0] = \skip_pipe[1] [0] | _025_;
  assign _026_ = _009_ & \mask_pipe[1] [0];
  assign _001_[0] = \en_pipe[1] [0] & _026_;
  assign _027_ = _008_ & \mask_pipe[1] [1];
  assign _001_[1] = \en_pipe[1] [1] & _027_;
  assign _028_ = _007_ & \mask_pipe[1] [2];
  assign _001_[2] = \en_pipe[1] [2] & _028_;
  assign _029_ = _006_ & \mask_pipe[1] [3];
  assign _001_[3] = \en_pipe[1] [3] & _029_;
  assign _030_ = _005_ & \mask_pipe[1] [4];
  assign _001_[4] = \en_pipe[1] [4] & _030_;
  assign _031_ = _004_ & \mask_pipe[1] [5];
  assign _001_[5] = \en_pipe[1] [5] & _031_;
  assign _032_ = _003_ & \mask_pipe[1] [6];
  assign _001_[6] = \en_pipe[1] [6] & _032_;
  assign _033_ = _002_ & \mask_pipe[1] [7];
  assign _001_[7] = \en_pipe[1] [7] & _033_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[0] <= 1'h0;
    else ck_out[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[1] <= 1'h0;
    else ck_out[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[2] <= 1'h0;
    else ck_out[2] <= _000_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[3] <= 1'h0;
    else ck_out[3] <= _000_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[4] <= 1'h0;
    else ck_out[4] <= _000_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[5] <= 1'h0;
    else ck_out[5] <= _000_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[6] <= 1'h0;
    else ck_out[6] <= _000_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) ck_out[7] <= 1'h0;
    else ck_out[7] <= _000_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[0] <= 1'h0;
    else error[0] <= _001_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[1] <= 1'h0;
    else error[1] <= _001_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[2] <= 1'h0;
    else error[2] <= _001_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[3] <= 1'h0;
    else error[3] <= _001_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[4] <= 1'h0;
    else error[4] <= _001_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[5] <= 1'h0;
    else error[5] <= _001_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[6] <= 1'h0;
    else error[6] <= _001_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) error[7] <= 1'h0;
    else error[7] <= _001_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [0] <= 1'h0;
    else \en_pipe[0] [0] <= ck_en[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [1] <= 1'h0;
    else \en_pipe[0] [1] <= ck_en[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [2] <= 1'h0;
    else \en_pipe[0] [2] <= ck_en[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [3] <= 1'h0;
    else \en_pipe[0] [3] <= ck_en[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [4] <= 1'h0;
    else \en_pipe[0] [4] <= ck_en[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [5] <= 1'h0;
    else \en_pipe[0] [5] <= ck_en[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [6] <= 1'h0;
    else \en_pipe[0] [6] <= ck_en[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[0] [7] <= 1'h0;
    else \en_pipe[0] [7] <= ck_en[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [0] <= 1'h0;
    else \en_pipe[1] [0] <= \en_pipe[0] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [1] <= 1'h0;
    else \en_pipe[1] [1] <= \en_pipe[0] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [2] <= 1'h0;
    else \en_pipe[1] [2] <= \en_pipe[0] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [3] <= 1'h0;
    else \en_pipe[1] [3] <= \en_pipe[0] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [4] <= 1'h0;
    else \en_pipe[1] [4] <= \en_pipe[0] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [5] <= 1'h0;
    else \en_pipe[1] [5] <= \en_pipe[0] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [6] <= 1'h0;
    else \en_pipe[1] [6] <= \en_pipe[0] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \en_pipe[1] [7] <= 1'h0;
    else \en_pipe[1] [7] <= \en_pipe[0] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [0] <= 1'h0;
    else \mask_pipe[0] [0] <= qck_mask[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [1] <= 1'h0;
    else \mask_pipe[0] [1] <= qck_mask[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [2] <= 1'h0;
    else \mask_pipe[0] [2] <= qck_mask[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [3] <= 1'h0;
    else \mask_pipe[0] [3] <= qck_mask[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [4] <= 1'h0;
    else \mask_pipe[0] [4] <= qck_mask[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [5] <= 1'h0;
    else \mask_pipe[0] [5] <= qck_mask[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [6] <= 1'h0;
    else \mask_pipe[0] [6] <= qck_mask[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[0] [7] <= 1'h0;
    else \mask_pipe[0] [7] <= qck_mask[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [0] <= 1'h0;
    else \mask_pipe[1] [0] <= \mask_pipe[0] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [1] <= 1'h0;
    else \mask_pipe[1] [1] <= \mask_pipe[0] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [2] <= 1'h0;
    else \mask_pipe[1] [2] <= \mask_pipe[0] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [3] <= 1'h0;
    else \mask_pipe[1] [3] <= \mask_pipe[0] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [4] <= 1'h0;
    else \mask_pipe[1] [4] <= \mask_pipe[0] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [5] <= 1'h0;
    else \mask_pipe[1] [5] <= \mask_pipe[0] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [6] <= 1'h0;
    else \mask_pipe[1] [6] <= \mask_pipe[0] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \mask_pipe[1] [7] <= 1'h0;
    else \mask_pipe[1] [7] <= \mask_pipe[0] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [0] <= 1'h0;
    else \skip_pipe[0] [0] <= skip_req[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [1] <= 1'h0;
    else \skip_pipe[0] [1] <= skip_req[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [2] <= 1'h0;
    else \skip_pipe[0] [2] <= skip_req[2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [3] <= 1'h0;
    else \skip_pipe[0] [3] <= skip_req[3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [4] <= 1'h0;
    else \skip_pipe[0] [4] <= skip_req[4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [5] <= 1'h0;
    else \skip_pipe[0] [5] <= skip_req[5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [6] <= 1'h0;
    else \skip_pipe[0] [6] <= skip_req[6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[0] [7] <= 1'h0;
    else \skip_pipe[0] [7] <= skip_req[7];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [0] <= 1'h0;
    else \skip_pipe[1] [0] <= \skip_pipe[0] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [1] <= 1'h0;
    else \skip_pipe[1] [1] <= \skip_pipe[0] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [2] <= 1'h0;
    else \skip_pipe[1] [2] <= \skip_pipe[0] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [3] <= 1'h0;
    else \skip_pipe[1] [3] <= \skip_pipe[0] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [4] <= 1'h0;
    else \skip_pipe[1] [4] <= \skip_pipe[0] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [5] <= 1'h0;
    else \skip_pipe[1] [5] <= \skip_pipe[0] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [6] <= 1'h0;
    else \skip_pipe[1] [6] <= \skip_pipe[0] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/qck_controller.sv:54.5-86.8" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) \skip_pipe[1] [7] <= 1'h0;
    else \skip_pipe[1] [7] <= \skip_pipe[0] [7];
  assign i = 32'd8;
endmodule
