/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/reg_init_ctrl.sv:6.1-66.10" *)
module reg_init_ctrl(clk, rst_n, reg0, reg1, reg2, init_done, handshake_start, handshake_end);
  wire _00_;
  wire _01_;
  wire _02_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:0.0-0.0|rtl/reg_init_ctrl.sv:40.9-57.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _03_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:0.0-0.0|rtl/reg_init_ctrl.sv:40.9-57.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _04_;
  (* src = "rtl/reg_init_ctrl.sv:11.18-11.21" *)
  input clk;
  wire clk;
  (* src = "rtl/reg_init_ctrl.sv:18.18-18.31" *)
  output handshake_end;
  reg handshake_end;
  (* src = "rtl/reg_init_ctrl.sv:17.18-17.33" *)
  output handshake_start;
  reg handshake_start;
  (* src = "rtl/reg_init_ctrl.sv:16.18-16.27" *)
  output init_done;
  wire init_done;
  (* src = "rtl/reg_init_ctrl.sv:13.25-13.29" *)
  output [31:0] reg0;
  wire [31:0] reg0;
  (* src = "rtl/reg_init_ctrl.sv:14.25-14.29" *)
  output [31:0] reg1;
  wire [31:0] reg1;
  (* src = "rtl/reg_init_ctrl.sv:15.25-15.29" *)
  output [31:0] reg2;
  wire [31:0] reg2;
  (* src = "rtl/reg_init_ctrl.sv:12.18-12.23" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/reg_init_ctrl.sv:22.13-22.18" *)
  reg [1:0] state;
  assign _04_[0] = ~state[0];
  assign _00_ = ~state[1];
  assign _01_ = _04_[0] | _00_;
  assign _02_ = state[0] | state[1];
  assign _03_ = ~_02_;
  assign _04_[1] = state[0] ^ state[1];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:29.1-59.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) handshake_start <= 1'h0;
    else if (!state[1]) handshake_start <= _03_;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:29.1-59.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) handshake_end <= 1'h0;
    else if (!_01_) handshake_end <= 1'h1;
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:29.1-59.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h0;
    else if (_01_) state[0] <= _04_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "rtl/reg_init_ctrl.sv:29.1-59.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else if (_01_) state[1] <= _04_[1];
  assign init_done = handshake_end;
  assign reg0 = 32'd3735928559;
  assign reg1 = 32'd4277009102;
  assign reg2 = 32'd3221344269;
endmodule
