/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/reg_err_detect.sv:7.1-162.10" *)
module reg_err_detect(clk, rst_n, reg_write, reg_read, reg_addr, reg_wdata, reg_rdata, reg_lock, access_valid, addr_range_chk, protocol_ok, lock_status, consistency_chk, err_flag, warn_flag, err_code, err_counter, warn_counter, alert_line, log_addr, log_data
, log_access_type, log_valid);
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire _000_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire [7:0] _001_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire [15:0] _002_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire _003_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire _004_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _176_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _177_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _178_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _179_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _180_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _181_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _182_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _183_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _184_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _185_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _186_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _187_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _188_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _189_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _190_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _191_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _192_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _193_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _194_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _195_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _196_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _197_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _198_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _199_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _200_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _201_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _202_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _203_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _204_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _205_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _206_;
  (* src = "rtl/reg_err_detect.sv:147.38-147.71" *)
  wire _207_;
  (* src = "rtl/reg_err_detect.sv:23.36-23.48" *)
  input access_valid;
  wire access_valid;
  (* src = "rtl/reg_err_detect.sv:24.36-24.50" *)
  input addr_range_chk;
  wire addr_range_chk;
  (* src = "rtl/reg_err_detect.sv:35.36-35.46" *)
  output alert_line;
  reg alert_line;
  (* src = "rtl/reg_err_detect.sv:12.36-12.39" *)
  input clk;
  wire clk;
  (* src = "rtl/reg_err_detect.sv:27.36-27.51" *)
  input consistency_chk;
  wire consistency_chk;
  (* src = "rtl/reg_err_detect.sv:32.36-32.44" *)
  output [7:0] err_code;
  wire [7:0] err_code;
  (* src = "rtl/reg_err_detect.sv:33.36-33.47" *)
  output [15:0] err_counter;
  reg [15:0] err_counter;
  (* src = "rtl/reg_err_detect.sv:30.36-30.44" *)
  output err_flag;
  reg err_flag;
  (* src = "rtl/reg_err_detect.sv:26.36-26.47" *)
  input lock_status;
  wire lock_status;
  (* src = "rtl/reg_err_detect.sv:40.36-40.51" *)
  output [2:0] log_access_type;
  reg [2:0] log_access_type;
  (* src = "rtl/reg_err_detect.sv:38.37-38.45" *)
  output [7:0] log_addr;
  reg [7:0] log_addr;
  (* src = "rtl/reg_err_detect.sv:39.37-39.45" *)
  output [31:0] log_data;
  reg [31:0] log_data;
  (* src = "rtl/reg_err_detect.sv:41.36-41.45" *)
  output log_valid;
  reg log_valid;
  (* src = "rtl/reg_err_detect.sv:25.36-25.47" *)
  input protocol_ok;
  wire protocol_ok;
  (* src = "rtl/reg_err_detect.sv:17.38-17.46" *)
  input [7:0] reg_addr;
  wire [7:0] reg_addr;
  (* src = "rtl/reg_err_detect.sv:20.36-20.44" *)
  input reg_lock;
  wire reg_lock;
  (* src = "rtl/reg_err_detect.sv:19.38-19.47" *)
  input [31:0] reg_rdata;
  wire [31:0] reg_rdata;
  (* src = "rtl/reg_err_detect.sv:16.36-16.44" *)
  input reg_read;
  wire reg_read;
  (* src = "rtl/reg_err_detect.sv:18.38-18.47" *)
  input [31:0] reg_wdata;
  wire [31:0] reg_wdata;
  (* src = "rtl/reg_err_detect.sv:15.36-15.45" *)
  input reg_write;
  wire reg_write;
  (* src = "rtl/reg_err_detect.sv:13.36-13.41" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/reg_err_detect.sv:75.6-75.20" *)
  wire stuck_at_fault;
  (* src = "rtl/reg_err_detect.sv:34.36-34.48" *)
  output [15:0] warn_counter;
  reg [15:0] warn_counter;
  (* src = "rtl/reg_err_detect.sv:31.36-31.45" *)
  output warn_flag;
  reg warn_flag;
  assign _008_ = ~access_valid;
  assign _009_ = ~protocol_ok;
  assign _010_ = ~err_counter[0];
  assign _011_ = ~consistency_chk;
  assign _012_ = ~reg_write;
  assign _013_ = ~reg_lock;
  assign _014_ = addr_range_chk & access_valid;
  assign _015_ = ~_014_;
  assign _016_ = lock_status | _013_;
  assign _017_ = _011_ & _016_;
  assign _018_ = ~_017_;
  assign _019_ = _009_ | _018_;
  assign _003_ = _015_ | _019_;
  assign _005_ = ~_003_;
  assign _020_ = addr_range_chk & protocol_ok;
  assign _021_ = ~_020_;
  assign _001_[2] = access_valid & _020_;
  assign _022_ = reg_read | reg_write;
  assign _023_ = err_flag | warn_flag;
  assign _004_ = _022_ | _023_;
  assign _024_ = ~_004_;
  assign _006_ = rst_n & _004_;
  assign _007_ = rst_n & _024_;
  assign _025_ = _012_ & reg_rdata[0];
  assign _026_ = reg_write & reg_wdata[0];
  assign _176_ = _025_ | _026_;
  assign _027_ = _012_ & reg_rdata[1];
  assign _028_ = reg_write & reg_wdata[1];
  assign _187_ = _027_ | _028_;
  assign _029_ = _012_ & reg_rdata[2];
  assign _030_ = reg_write & reg_wdata[2];
  assign _198_ = _029_ | _030_;
  assign _031_ = _012_ & reg_rdata[3];
  assign _032_ = reg_write & reg_wdata[3];
  assign _201_ = _031_ | _032_;
  assign _033_ = _012_ & reg_rdata[4];
  assign _034_ = reg_write & reg_wdata[4];
  assign _202_ = _033_ | _034_;
  assign _035_ = _012_ & reg_rdata[5];
  assign _036_ = reg_write & reg_wdata[5];
  assign _203_ = _035_ | _036_;
  assign _037_ = _012_ & reg_rdata[6];
  assign _038_ = reg_write & reg_wdata[6];
  assign _204_ = _037_ | _038_;
  assign _039_ = _012_ & reg_rdata[7];
  assign _040_ = reg_write & reg_wdata[7];
  assign _205_ = _039_ | _040_;
  assign _041_ = _012_ & reg_rdata[8];
  assign _042_ = reg_write & reg_wdata[8];
  assign _206_ = _041_ | _042_;
  assign _043_ = _012_ & reg_rdata[9];
  assign _044_ = reg_write & reg_wdata[9];
  assign _207_ = _043_ | _044_;
  assign _045_ = _012_ & reg_rdata[10];
  assign _046_ = reg_write & reg_wdata[10];
  assign _177_ = _045_ | _046_;
  assign _047_ = _012_ & reg_rdata[11];
  assign _048_ = reg_write & reg_wdata[11];
  assign _178_ = _047_ | _048_;
  assign _049_ = _012_ & reg_rdata[12];
  assign _050_ = reg_write & reg_wdata[12];
  assign _179_ = _049_ | _050_;
  assign _051_ = _012_ & reg_rdata[13];
  assign _052_ = reg_write & reg_wdata[13];
  assign _180_ = _051_ | _052_;
  assign _053_ = _012_ & reg_rdata[14];
  assign _054_ = reg_write & reg_wdata[14];
  assign _181_ = _053_ | _054_;
  assign _055_ = _012_ & reg_rdata[15];
  assign _056_ = reg_write & reg_wdata[15];
  assign _182_ = _055_ | _056_;
  assign _057_ = _012_ & reg_rdata[16];
  assign _058_ = reg_write & reg_wdata[16];
  assign _183_ = _057_ | _058_;
  assign _059_ = _012_ & reg_rdata[17];
  assign _060_ = reg_write & reg_wdata[17];
  assign _184_ = _059_ | _060_;
  assign _061_ = _012_ & reg_rdata[18];
  assign _062_ = reg_write & reg_wdata[18];
  assign _185_ = _061_ | _062_;
  assign _063_ = _012_ & reg_rdata[19];
  assign _064_ = reg_write & reg_wdata[19];
  assign _186_ = _063_ | _064_;
  assign _065_ = _012_ & reg_rdata[20];
  assign _066_ = reg_write & reg_wdata[20];
  assign _188_ = _065_ | _066_;
  assign _067_ = _012_ & reg_rdata[21];
  assign _068_ = reg_write & reg_wdata[21];
  assign _189_ = _067_ | _068_;
  assign _069_ = _012_ & reg_rdata[22];
  assign _070_ = reg_write & reg_wdata[22];
  assign _190_ = _069_ | _070_;
  assign _071_ = _012_ & reg_rdata[23];
  assign _072_ = reg_write & reg_wdata[23];
  assign _191_ = _071_ | _072_;
  assign _073_ = _012_ & reg_rdata[24];
  assign _074_ = reg_write & reg_wdata[24];
  assign _192_ = _073_ | _074_;
  assign _075_ = _012_ & reg_rdata[25];
  assign _076_ = reg_write & reg_wdata[25];
  assign _193_ = _075_ | _076_;
  assign _077_ = _012_ & reg_rdata[26];
  assign _078_ = reg_write & reg_wdata[26];
  assign _194_ = _077_ | _078_;
  assign _079_ = _012_ & reg_rdata[27];
  assign _080_ = reg_write & reg_wdata[27];
  assign _195_ = _079_ | _080_;
  assign _081_ = _012_ & reg_rdata[28];
  assign _082_ = reg_write & reg_wdata[28];
  assign _196_ = _081_ | _082_;
  assign _083_ = _012_ & reg_rdata[29];
  assign _084_ = reg_write & reg_wdata[29];
  assign _197_ = _083_ | _084_;
  assign _085_ = _012_ & reg_rdata[30];
  assign _086_ = reg_write & reg_wdata[30];
  assign _199_ = _085_ | _086_;
  assign _087_ = _012_ & reg_rdata[31];
  assign _088_ = reg_write & reg_wdata[31];
  assign _200_ = _087_ | _088_;
  assign _000_ = _014_ & _019_;
  assign _089_ = _009_ | _017_;
  assign _158_ = addr_range_chk & _089_;
  assign _001_[0] = _008_ | _158_;
  assign _090_ = consistency_chk & _016_;
  assign _159_ = _021_ | _090_;
  assign _001_[1] = access_valid & _159_;
  assign _091_ = warn_counter[0] | consistency_chk;
  assign _160_ = ~_091_;
  assign _092_ = warn_counter[0] & warn_counter[1];
  assign _093_ = warn_counter[0] ^ warn_counter[1];
  assign _167_ = _011_ & _093_;
  assign _094_ = warn_counter[2] & _092_;
  assign _095_ = warn_counter[2] ^ _092_;
  assign _168_ = _011_ & _095_;
  assign _096_ = warn_counter[3] & _094_;
  assign _097_ = warn_counter[3] ^ _094_;
  assign _169_ = _011_ & _097_;
  assign _098_ = warn_counter[4] & _096_;
  assign _099_ = warn_counter[4] ^ _096_;
  assign _170_ = _011_ & _099_;
  assign _100_ = warn_counter[5] & _098_;
  assign _101_ = warn_counter[5] | _098_;
  assign _102_ = consistency_chk | _100_;
  assign _103_ = ~_102_;
  assign _171_ = _101_ & _103_;
  assign _104_ = warn_counter[6] & _100_;
  assign _105_ = warn_counter[6] ^ _100_;
  assign _172_ = _011_ & _105_;
  assign _106_ = warn_counter[7] & _104_;
  assign _107_ = warn_counter[7] ^ _104_;
  assign _173_ = _011_ & _107_;
  assign _108_ = warn_counter[8] & _106_;
  assign _109_ = warn_counter[8] ^ _106_;
  assign _174_ = _011_ & _109_;
  assign _110_ = warn_counter[9] & _108_;
  assign _111_ = warn_counter[9] | _108_;
  assign _112_ = consistency_chk | _110_;
  assign _113_ = ~_112_;
  assign _175_ = _111_ & _113_;
  assign _114_ = warn_counter[10] & _110_;
  assign _115_ = warn_counter[10] ^ _110_;
  assign _161_ = _011_ & _115_;
  assign _116_ = warn_counter[11] & _114_;
  assign _117_ = warn_counter[11] ^ _114_;
  assign _162_ = _011_ & _117_;
  assign _118_ = warn_counter[12] & _116_;
  assign _119_ = warn_counter[12] ^ _116_;
  assign _163_ = _011_ & _119_;
  assign _120_ = warn_counter[13] & _118_;
  assign _121_ = warn_counter[13] ^ _118_;
  assign _164_ = _011_ & _121_;
  assign _122_ = warn_counter[14] & _120_;
  assign _123_ = warn_counter[14] ^ _120_;
  assign _165_ = _011_ & _123_;
  assign _124_ = warn_counter[15] ^ _122_;
  assign _166_ = _011_ & _124_;
  assign _002_[0] = _010_ & _003_;
  assign _125_ = err_counter[0] & err_counter[1];
  assign _126_ = err_counter[0] ^ err_counter[1];
  assign _002_[1] = _003_ & _126_;
  assign _127_ = err_counter[2] & _125_;
  assign _128_ = err_counter[2] ^ _125_;
  assign _002_[2] = _003_ & _128_;
  assign _129_ = err_counter[3] & _127_;
  assign _130_ = err_counter[3] ^ _127_;
  assign _002_[3] = _003_ & _130_;
  assign _131_ = err_counter[4] & _129_;
  assign _132_ = err_counter[4] ^ _129_;
  assign _002_[4] = _003_ & _132_;
  assign _133_ = err_counter[5] & _131_;
  assign _134_ = ~_133_;
  assign _135_ = err_counter[5] | _131_;
  assign _136_ = _003_ & _135_;
  assign _002_[5] = _134_ & _136_;
  assign _137_ = err_counter[6] & _133_;
  assign _138_ = err_counter[6] ^ _133_;
  assign _002_[6] = _003_ & _138_;
  assign _139_ = err_counter[7] & _137_;
  assign _140_ = err_counter[7] ^ _137_;
  assign _002_[7] = _003_ & _140_;
  assign _141_ = err_counter[8] & _139_;
  assign _142_ = err_counter[8] ^ _139_;
  assign _002_[8] = _003_ & _142_;
  assign _143_ = err_counter[9] & _141_;
  assign _144_ = ~_143_;
  assign _145_ = err_counter[9] | _141_;
  assign _146_ = _003_ & _145_;
  assign _002_[9] = _144_ & _146_;
  assign _147_ = err_counter[10] & _143_;
  assign _148_ = err_counter[10] ^ _143_;
  assign _002_[10] = _003_ & _148_;
  assign _149_ = err_counter[11] & _147_;
  assign _150_ = err_counter[11] ^ _147_;
  assign _002_[11] = _003_ & _150_;
  assign _151_ = err_counter[12] & _149_;
  assign _152_ = err_counter[12] ^ _149_;
  assign _002_[12] = _003_ & _152_;
  assign _153_ = err_counter[13] & _151_;
  assign _154_ = err_counter[13] ^ _151_;
  assign _002_[13] = _003_ & _154_;
  assign _155_ = err_counter[14] & _153_;
  assign _156_ = err_counter[14] ^ _153_;
  assign _002_[14] = _003_ & _156_;
  assign _157_ = err_counter[15] ^ _155_;
  assign _002_[15] = _003_ & _157_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_flag <= 1'h0;
    else err_flag <= _003_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_flag <= 1'h0;
    else warn_flag <= _005_;
  reg \err_code_reg[0] ;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \err_code_reg[0]  <= 1'h0;
    else \err_code_reg[0]  <= _001_[0];
  assign err_code[0] = \err_code_reg[0] ;
  reg \err_code_reg[1] ;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \err_code_reg[1]  <= 1'h0;
    else \err_code_reg[1]  <= _001_[1];
  assign err_code[1] = \err_code_reg[1] ;
  reg \err_code_reg[2] ;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \err_code_reg[2]  <= 1'h0;
    else \err_code_reg[2]  <= _001_[2];
  assign err_code[2] = \err_code_reg[2] ;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[0] <= 1'h0;
    else if (!_003_) warn_counter[0] <= _160_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[1] <= 1'h0;
    else if (!_003_) warn_counter[1] <= _167_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[2] <= 1'h0;
    else if (!_003_) warn_counter[2] <= _168_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[3] <= 1'h0;
    else if (!_003_) warn_counter[3] <= _169_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[4] <= 1'h0;
    else if (!_003_) warn_counter[4] <= _170_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[5] <= 1'h0;
    else if (!_003_) warn_counter[5] <= _171_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[6] <= 1'h0;
    else if (!_003_) warn_counter[6] <= _172_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[7] <= 1'h0;
    else if (!_003_) warn_counter[7] <= _173_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[8] <= 1'h0;
    else if (!_003_) warn_counter[8] <= _174_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[9] <= 1'h0;
    else if (!_003_) warn_counter[9] <= _175_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[10] <= 1'h0;
    else if (!_003_) warn_counter[10] <= _161_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[11] <= 1'h0;
    else if (!_003_) warn_counter[11] <= _162_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[12] <= 1'h0;
    else if (!_003_) warn_counter[12] <= _163_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[13] <= 1'h0;
    else if (!_003_) warn_counter[13] <= _164_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[14] <= 1'h0;
    else if (!_003_) warn_counter[14] <= _165_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) warn_counter[15] <= 1'h0;
    else if (!_003_) warn_counter[15] <= _166_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[0] <= reg_addr[0];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[1] <= reg_addr[1];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[2] <= reg_addr[2];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[3] <= reg_addr[3];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[4] <= reg_addr[4];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[5] <= reg_addr[5];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[6] <= reg_addr[6];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_addr[7] <= reg_addr[7];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alert_line <= 1'h0;
    else alert_line <= _000_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[0] <= _176_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[1] <= _187_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[2] <= _198_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[3] <= _201_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[4] <= _202_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[5] <= _203_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[6] <= _204_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[7] <= _205_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[8] <= _206_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[9] <= _207_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[10] <= _177_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[11] <= _178_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[12] <= _179_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[13] <= _180_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[14] <= _181_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[15] <= _182_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[16] <= _183_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[17] <= _184_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[18] <= _185_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[19] <= _186_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[20] <= _188_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[21] <= _189_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[22] <= _190_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[23] <= _191_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[24] <= _192_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[25] <= _193_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[26] <= _194_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[27] <= _195_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[28] <= _196_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[29] <= _197_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[30] <= _199_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_006_) log_data[31] <= _200_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_007_)
      if (!access_valid) log_access_type[0] <= 1'h1;
      else log_access_type[0] <= _158_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_007_)
      if (!access_valid) log_access_type[1] <= 1'h0;
      else log_access_type[1] <= _159_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) log_valid <= 1'h0;
    else log_valid <= _004_;
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[0] <= 1'h0;
    else if (_003_) err_counter[0] <= _002_[0];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[1] <= 1'h0;
    else if (_003_) err_counter[1] <= _002_[1];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[2] <= 1'h0;
    else if (_003_) err_counter[2] <= _002_[2];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[3] <= 1'h0;
    else if (_003_) err_counter[3] <= _002_[3];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[4] <= 1'h0;
    else if (_003_) err_counter[4] <= _002_[4];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[5] <= 1'h0;
    else if (_003_) err_counter[5] <= _002_[5];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[6] <= 1'h0;
    else if (_003_) err_counter[6] <= _002_[6];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[7] <= 1'h0;
    else if (_003_) err_counter[7] <= _002_[7];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[8] <= 1'h0;
    else if (_003_) err_counter[8] <= _002_[8];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[9] <= 1'h0;
    else if (_003_) err_counter[9] <= _002_[9];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[10] <= 1'h0;
    else if (_003_) err_counter[10] <= _002_[10];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[11] <= 1'h0;
    else if (_003_) err_counter[11] <= _002_[11];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[12] <= 1'h0;
    else if (_003_) err_counter[12] <= _002_[12];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[13] <= 1'h0;
    else if (_003_) err_counter[13] <= _002_[13];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[14] <= 1'h0;
    else if (_003_) err_counter[14] <= _002_[14];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) err_counter[15] <= 1'h0;
    else if (_003_) err_counter[15] <= _002_[15];
  (* src = "rtl/reg_err_detect.sv:79.1-156.4" *)
  always @(posedge clk)
    if (_007_)
      if (!_001_[2]) log_access_type[2] <= 1'h0;
      else log_access_type[2] <= 1'h1;
  assign _001_[7:3] = 5'h00;
  assign err_code[7:3] = 5'h00;
  assign stuck_at_fault = 1'h1;
endmodule
