/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/sec_reg_lock.sv:6.1-90.10" *)
module sec_reg_lock(clk, rst_n, key_in, key_valid, set_access_lvl, access_lvl_valid, lock_req, reg_write_req, reg_write_data, locked, access_level, write_success, error_flag, alert_flag, reg_data, lock_state_update, lock_cfg_alert);
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  wire _000_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  wire _001_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  wire _002_;
  (* src = "rtl/sec_reg_lock.sv:67.17-67.63" *)
  wire _003_;
  (* src = "rtl/sec_reg_lock.sv:53.21-53.40" *)
  wire _004_;
  (* src = "rtl/sec_reg_lock.sv:51.17-51.46" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  (* src = "rtl/sec_reg_lock.sv:61.27-61.34" *)
  wire _042_;
  (* src = "rtl/sec_reg_lock.sv:21.34-21.46" *)
  output [1:0] access_level;
  reg [1:0] access_level;
  (* src = "rtl/sec_reg_lock.sv:16.34-16.50" *)
  input access_lvl_valid;
  wire access_lvl_valid;
  (* src = "rtl/sec_reg_lock.sv:24.34-24.44" *)
  output alert_flag;
  reg alert_flag;
  (* src = "rtl/sec_reg_lock.sv:11.34-11.37" *)
  input clk;
  wire clk;
  (* src = "rtl/sec_reg_lock.sv:23.34-23.44" *)
  output error_flag;
  wire error_flag;
  (* src = "rtl/sec_reg_lock.sv:34.37-34.54" *)
  reg key_authenticated;
  (* src = "rtl/sec_reg_lock.sv:13.34-13.40" *)
  input [31:0] key_in;
  wire [31:0] key_in;
  (* src = "rtl/sec_reg_lock.sv:14.34-14.43" *)
  input key_valid;
  wire key_valid;
  (* src = "rtl/sec_reg_lock.sv:28.34-28.48" *)
  output lock_cfg_alert;
  reg lock_cfg_alert;
  (* src = "rtl/sec_reg_lock.sv:17.34-17.42" *)
  input lock_req;
  wire lock_req;
  (* src = "rtl/sec_reg_lock.sv:27.34-27.51" *)
  output lock_state_update;
  reg lock_state_update;
  (* src = "rtl/sec_reg_lock.sv:20.34-20.40" *)
  output locked;
  reg locked;
  (* src = "rtl/sec_reg_lock.sv:25.34-25.42" *)
  output [31:0] reg_data;
  reg [31:0] reg_data;
  (* src = "rtl/sec_reg_lock.sv:19.34-19.48" *)
  input [31:0] reg_write_data;
  wire [31:0] reg_write_data;
  (* src = "rtl/sec_reg_lock.sv:18.34-18.47" *)
  input reg_write_req;
  wire reg_write_req;
  (* src = "rtl/sec_reg_lock.sv:12.34-12.39" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl/sec_reg_lock.sv:15.34-15.48" *)
  input [1:0] set_access_lvl;
  wire [1:0] set_access_lvl;
  (* src = "rtl/sec_reg_lock.sv:22.34-22.47" *)
  output write_success;
  reg write_success;
  assign _042_ = ~locked;
  assign _006_ = key_in[27] & key_in[28];
  assign _007_ = key_in[30] & key_in[31];
  assign _008_ = _006_ & _007_;
  assign _009_ = key_in[21] & key_in[23];
  assign _010_ = key_in[25] & key_in[26];
  assign _011_ = _009_ & _010_;
  assign _012_ = _008_ & _011_;
  assign _013_ = key_in[20] | key_in[22];
  assign _014_ = key_in[24] | key_in[29];
  assign _015_ = _013_ | _014_;
  assign _016_ = key_in[4] | key_in[8];
  assign _017_ = key_in[14] | key_in[17];
  assign _018_ = _016_ | _017_;
  assign _019_ = _015_ | _018_;
  assign _020_ = ~_019_;
  assign _021_ = _012_ & _020_;
  assign _022_ = key_in[5] & key_in[6];
  assign _023_ = key_in[7] & key_in[9];
  assign _024_ = _022_ & _023_;
  assign _025_ = key_in[0] & key_in[1];
  assign _026_ = key_in[2] & key_in[3];
  assign _027_ = _025_ & _026_;
  assign _028_ = _024_ & _027_;
  assign _029_ = key_in[15] & key_in[16];
  assign _030_ = key_in[18] & key_in[19];
  assign _031_ = _029_ & _030_;
  assign _032_ = key_in[10] & key_in[11];
  assign _033_ = key_in[12] & key_in[13];
  assign _034_ = _032_ & _033_;
  assign _035_ = _031_ & _034_;
  assign _036_ = _028_ & _035_;
  assign _004_ = _021_ & _036_;
  assign _005_ = key_valid | access_lvl_valid;
  assign _037_ = access_level[1] | access_level[0];
  assign _038_ = ~_037_;
  assign _039_ = _042_ & _037_;
  assign _040_ = locked | _038_;
  assign _000_ = reg_write_req & _040_;
  assign _002_ = reg_write_req & _039_;
  assign _001_ = lock_req & key_authenticated;
  assign _041_ = access_lvl_valid & key_authenticated;
  assign _003_ = _042_ & _041_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) access_level[0] <= 1'h0;
    else if (_003_) access_level[0] <= set_access_lvl[0];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) access_level[1] <= 1'h0;
    else if (_003_) access_level[1] <= set_access_lvl[1];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_success <= 1'h0;
    else write_success <= _002_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) alert_flag <= 1'h0;
    else alert_flag <= _000_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) lock_cfg_alert <= 1'h0;
    else if (!_002_) lock_cfg_alert <= _000_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) lock_state_update <= 1'h0;
    else lock_state_update <= _001_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) locked <= 1'h1;
    else if (_001_) locked <= _042_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) key_authenticated <= 1'h0;
    else if (_005_) key_authenticated <= _004_;
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[0] <= 1'h0;
    else if (_002_) reg_data[0] <= reg_write_data[0];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[1] <= 1'h0;
    else if (_002_) reg_data[1] <= reg_write_data[1];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[2] <= 1'h0;
    else if (_002_) reg_data[2] <= reg_write_data[2];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[3] <= 1'h0;
    else if (_002_) reg_data[3] <= reg_write_data[3];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[4] <= 1'h0;
    else if (_002_) reg_data[4] <= reg_write_data[4];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[5] <= 1'h0;
    else if (_002_) reg_data[5] <= reg_write_data[5];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[6] <= 1'h0;
    else if (_002_) reg_data[6] <= reg_write_data[6];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[7] <= 1'h0;
    else if (_002_) reg_data[7] <= reg_write_data[7];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[8] <= 1'h0;
    else if (_002_) reg_data[8] <= reg_write_data[8];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[9] <= 1'h0;
    else if (_002_) reg_data[9] <= reg_write_data[9];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[10] <= 1'h0;
    else if (_002_) reg_data[10] <= reg_write_data[10];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[11] <= 1'h0;
    else if (_002_) reg_data[11] <= reg_write_data[11];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[12] <= 1'h0;
    else if (_002_) reg_data[12] <= reg_write_data[12];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[13] <= 1'h0;
    else if (_002_) reg_data[13] <= reg_write_data[13];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[14] <= 1'h0;
    else if (_002_) reg_data[14] <= reg_write_data[14];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[15] <= 1'h0;
    else if (_002_) reg_data[15] <= reg_write_data[15];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[16] <= 1'h0;
    else if (_002_) reg_data[16] <= reg_write_data[16];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[17] <= 1'h0;
    else if (_002_) reg_data[17] <= reg_write_data[17];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[18] <= 1'h0;
    else if (_002_) reg_data[18] <= reg_write_data[18];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[19] <= 1'h0;
    else if (_002_) reg_data[19] <= reg_write_data[19];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[20] <= 1'h0;
    else if (_002_) reg_data[20] <= reg_write_data[20];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[21] <= 1'h0;
    else if (_002_) reg_data[21] <= reg_write_data[21];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[22] <= 1'h0;
    else if (_002_) reg_data[22] <= reg_write_data[22];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[23] <= 1'h0;
    else if (_002_) reg_data[23] <= reg_write_data[23];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[24] <= 1'h0;
    else if (_002_) reg_data[24] <= reg_write_data[24];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[25] <= 1'h0;
    else if (_002_) reg_data[25] <= reg_write_data[25];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[26] <= 1'h0;
    else if (_002_) reg_data[26] <= reg_write_data[26];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[27] <= 1'h0;
    else if (_002_) reg_data[27] <= reg_write_data[27];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[28] <= 1'h0;
    else if (_002_) reg_data[28] <= reg_write_data[28];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[29] <= 1'h0;
    else if (_002_) reg_data[29] <= reg_write_data[29];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[30] <= 1'h0;
    else if (_002_) reg_data[30] <= reg_write_data[30];
  (* src = "rtl/sec_reg_lock.sv:37.5-89.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_data[31] <= 1'h0;
    else if (_002_) reg_data[31] <= reg_write_data[31];
  assign error_flag = alert_flag;
endmodule
